Repository apache/doris-website, pull requests merged in 2024-12, with the labels that each got.

#1427 [improvement](ccr) improve overview of ccr
  docs/admin-manual/data-admin/ccr/manual.md
  docs/admin-manual/data-admin/ccr/overview.md
  docs/admin-manual/data-admin/ccr/quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/quickstart.md
Labels: has comments

#1412 [doc](update) modify the example for UPDATE usage
  docs/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/unique-update.md
  versioned_docs/version-2.0/data-operate/update/unique-update.md
  versioned_docs/version-2.1/data-operate/update/unique-update.md
  versioned_docs/version-3.0/data-operate/update/unique-update.md
Labels: request review

#1415 K8s decoupled doc
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-cg.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-fe.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/cluster-operation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-cg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-fe.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-ms.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/install-env.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/cluster-operation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-env.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/cluster-operation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-cg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-fe.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-ms.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/install-env.md
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-cg.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-fe.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-ms.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
Labels: request review

#1472 Update what-is-apache-doris.md
  common_docs_zh/gettingStarted/what-is-apache-doris.md
Labels: approved

#1430 Update es.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/es.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/database/es.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/es.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/es.md
  versioned_docs/version-2.0/lakehouse/database/es.md
  versioned_docs/version-2.1/lakehouse/database/es.md
  versioned_docs/version-3.0/lakehouse/database/es.md
Labels: approved

#1433 [auth]change default log level of ranger to warn
  docs/admin-manual/auth/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/ranger.md
  versioned_docs/version-2.1/admin-manual/auth/ranger.md
  versioned_docs/version-3.0/admin-manual/auth/ranger.md
Labels: approved

#1393 [doc](update) rewrite update overview doc
  docs/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-overview.md
  versioned_docs/version-2.0/data-operate/update/update-overview.md
  versioned_docs/version-2.1/data-operate/update/update-overview.md
  versioned_docs/version-3.0/data-operate/update/update-overview.md
Labels: approved, Reviewed

#1490 [doc](delete) update the examples of batch delete to reference links to stream load manual
  docs/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/batch-delete-manual.md
  versioned_docs/version-2.0/data-operate/delete/batch-delete-manual.md
  versioned_docs/version-2.1/data-operate/delete/batch-delete-manual.md
  versioned_docs/version-3.0/data-operate/delete/batch-delete-manual.md
Labels: approved

#1486 [doc] fix the wrong link in the tpch document
  benchmark/tpch.md
  common_docs_zh/benchmark/tpch.md
Labels: approved

#1439 fix name SQL conflict error in point query docs
  docs/query-acceleration/high-concurrent-point-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/high-concurrent-point-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/high-concurrent-point-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/high-concurrent-point-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/high-concurrent-point-query.md
  versioned_docs/version-2.0/query/high-concurrent-point-query.md
  versioned_docs/version-2.1/query-acceleration/high-concurrent-point-query.md
  versioned_docs/version-3.0/query-acceleration/high-concurrent-point-query.md
Labels: approved

#1388 [opt](cte) indicate not support recursive cte
  docs/query-data/cte.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/cte.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/query-data/cte.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/cte.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/cte.md
  versioned_docs/version-2.0/query/query-data/cte.md
  versioned_docs/version-2.1/query-data/cte.md
  versioned_docs/version-3.0/query-data/cte.md
Labels: Reviewed

#1493 [Doc](benchmark) update 2.1 benchmark doc.
  benchmark/ssb.md
  benchmark/tpcds.md
  benchmark/tpch.md
  common_docs_zh/benchmark/ssb.md
  common_docs_zh/benchmark/tpcds.md
  common_docs_zh/benchmark/tpch.md
  static/images/tpcds_2.1.png
  static/images/tpch_2.1.png
Labels: approved

#1502 [community] Add special thanks of community
  community/thanks.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/doris-announcement/announcement-2401.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/thanks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  sidebarsCommunity.json
  versioned_docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW-JOB.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
  versioned_docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  versioned_sidebars/version-2.1-sidebars.json
Labels: approved

#1504 [update] Fix typo of MySQL Compatibility
  docs/query-data/mysql-compatibility.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/mysql-compatibility.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/mysql-compatibility.md
  versioned_docs/version-2.0/query/query-data/mysql-compatibility.md
  versioned_docs/version-2.1/query-data/mysql-compatibility.md
  versioned_docs/version-3.0/query-data/mysql-compatibility.md
Labels: approved

#1392 [opt](sql cache) Reorganize the chapter on SQL Cache
  docs/query-acceleration/sql-cache-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/sql-cache-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/sql-cache-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/sql-cache-manual.md
  versioned_docs/version-2.1/query-acceleration/sql-cache-manual.md
  versioned_docs/version-3.0/query-acceleration/sql-cache-manual.md
Labels: approved, Reviewed

#1507 [fix] Fix deadlink of complex data type
  docs/query-data/complex-type.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/complex-type.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/complex-type.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/complex-type.md
  versioned_docs/version-2.1/query-data/complex-type.md
  versioned_docs/version-3.0/query-data/complex-type.md
Labels: approved

#1478 [fix] add the window-function doc and multi-dimensional-analytics doc sql used table data
  docs/query-data/multi-dimensional-analytics.md
  docs/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/multi-dimensional-analytics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/multi-dimensional-analytics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/multi-dimensional-analytics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/window-function.md
  versioned_docs/version-2.1/query-data/multi-dimensional-analytics.md
  versioned_docs/version-2.1/query-data/window-function.md
  versioned_docs/version-3.0/query-data/multi-dimensional-analytics.md
  versioned_docs/version-3.0/query-data/window-function.md
Labels: approved

#1438 [doc](update) modify update-of-unique-model.md
  docs/data-operate/update/update-of-unique-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-unique-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/update/update-of-unique-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-of-unique-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-of-unique-model.md
  versioned_docs/version-2.0/data-operate/update/update-of-unique-model.md
  versioned_docs/version-2.1/data-operate/update/update-of-unique-model.md
  versioned_docs/version-3.0/data-operate/update/update-of-unique-model.md
Labels: Reviewed

#1500 [refactor](k8s)K8s coupled refactor arch
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/access-cluster.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-cluster.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-operator.md
  docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  docs/install/cluster-deployment/k8s-deploy/install-env.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/access-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/cluster-operation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-operator.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/access-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/cluster-operation.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-doris-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-doris-operator.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-env.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/access-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-operator.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
  sidebars.json
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/access-cluster.md
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-doris-cluster.md
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-doris-operator.md
  versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/access-cluster.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-cluster.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-doris-operator.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
  versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/install-env.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review

#1372 [docs](load) restructure broker load docs
  docs/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
Labels: Reviewed

#1379 [docs](load) split insert into values and insert into select
  docs/data-operate/import/import-way/insert-into-manual.md
  docs/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: has comments, Reviewed

#1545 [fix] Fix title of small file mananger
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/small-file-mgr.md
Labels: approved

#1550 [fix](ccr) update ccr dir
  sidebars.json
Labels: approved

#1512 [Doc](benchmark) update 3.0 benchmark doc.
  docs/benchmark/ssb.md
  docs/benchmark/tpcds.md
  docs/benchmark/tpch.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/benchmark/ssb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/benchmark/tpcds.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/benchmark/tpch.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/benchmark/ssb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/benchmark/tpcds.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/benchmark/tpch.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/benchmark/ssb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/benchmark/tpcds.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/benchmark/tpch.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/benchmark/ssb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/benchmark/tpcds.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/benchmark/tpch.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/benchmark/ssb.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/benchmark/tpcds.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/benchmark/tpch.md
  static/images/tpcds_2.1.png
  static/images/tpcds_3.0.png
  static/images/tpch_2.1.png
  static/images/tpch_3.0.png
  versioned_docs/version-1.2/benchmark/ssb.md
  versioned_docs/version-1.2/benchmark/tpcds.md
  versioned_docs/version-1.2/benchmark/tpch.md
  versioned_docs/version-2.0/benchmark/ssb.md
  versioned_docs/version-2.0/benchmark/tpcds.md
  versioned_docs/version-2.0/benchmark/tpch.md
  versioned_docs/version-2.1/benchmark/ssb.md
  versioned_docs/version-2.1/benchmark/tpcds.md
  versioned_docs/version-2.1/benchmark/tpch.md
  versioned_docs/version-3.0/benchmark/ssb.md
  versioned_docs/version-3.0/benchmark/tpcds.md
  versioned_docs/version-3.0/benchmark/tpch.md
Labels: approved

#1549 [fix] Fix title of Workload Group EN Version
  docs/admin-manual/workload-management/sql-blocking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/query-admin/kill-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/analysis-diagnosis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/best-practice/group-workload-groups.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/best-practice/workload-group-best-practice.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/compute-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/job-scheduler.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/kill-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/resource-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/spill-disk.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/sql-blocking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-management-summary.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/scheduler/job-scheduler.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/query-admin/kill-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/analysis-diagnosis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/best-practice/group-workload-groups.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/best-practice/workload-group-best-practice.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/compute-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/job-scheduler.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/kill-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/resource-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/spill-disk.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/sql-blocking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/workload-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/workload-management-summary.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/scheduler/job-scheduler.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/query-admin/kill-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/analysis-diagnosis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/best-practice/group-workload-groups.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/best-practice/workload-group-best-practice.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/job-scheduler.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/kill-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/resource-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/spill-disk.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/sql-blocking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/workload-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/workload-management-summary.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-compute-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/scheduler/job-scheduler.md
  sidebars.json
  versioned_docs/version-2.1/admin-manual/workload-management/sql-blocking.md
  versioned_docs/version-3.0/admin-manual/workload-management/sql-blocking.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1530 [doc](delete) update delete manual
  docs/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/DELETE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/DELETE.md
  versioned_docs/version-2.0/data-operate/delete/delete-manual.md
Labels: approved, Reviewed

#1533 [doc]update encryption-funtions document link
  docs/admin-manual/auth/encryption-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/encryption-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/encryption-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/encryption-function.md
  versioned_docs/version-2.1/admin-manual/auth/encryption-function.md
  versioned_docs/version-3.0/admin-manual/auth/encryption-function.md
Labels: approved

#1551 [Fix](CI) Support remove spare suffix of links in documents
  check_move.py
Labels: approved

#1557 [fix](routine-load) fix wrong properties
  docs/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
Labels: approved

#1556 Update ccr feature details
  docs/admin-manual/data-admin/ccr/feature.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/feature.md
Labels: request review

#1476 Add enable_batch_download config to BE
  docs/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/be-config.md
  versioned_docs/version-2.1/admin-manual/config/be-config.md
  versioned_docs/version-3.0/admin-manual/config/be-config.md
Labels: has comments, Need update version-2.1, Need update version-3.0

#1555 [fix] Fix modify frontend hostname
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/MODIFY-FRONTEND-HOSTNAME.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/MODIFY-FRONTEND-HOSTNAME.md
Labels: approved

#1573 Add pipeline execution document
  docs/query-acceleration/pipeline-execution-engine.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/pipeline-execution-engine.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/pipeline-execution-engine.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/pipeline-execution-engine.md
  static/images/pip_exec_1.png
  static/images/pip_exec_2.png
  static/images/pip_exec_3.png
  static/images/pip_exec_4.png
  static/images/pip_exec_5.png
  static/images/pip_exec_6.png
  static/images/pip_exec_7.png
  versioned_docs/version-2.1/query-acceleration/pipeline-execution-engine.md
  versioned_docs/version-3.0/query-acceleration/pipeline-execution-engine.md
Labels: request review

#1503 (cloud) Update arm support of cloud mode
  docs/compute-storage-decoupled/compilation-and-deployment.md
  docs/install/source-install/compilation-arm.mdx
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/compilation-and-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/source-install/compilation-arm.mdx
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/source-install/compilation-arm.mdx
  static/images/compute-storage-decoupled-zh.png
  static/images/compute-storage-decoupled.png
  versioned_docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
  versioned_docs/version-3.0/install/source-install/compilation-arm.mdx
Labels: bug, approved

#1489 [bug][recover] fix example
  docs/sql-manual/sql-statements/Database-Administration-Statements/RECOVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Database-Administration-Statements/RECOVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/RECOVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/recycle/RECOVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/recycle/RECOVER.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/RECOVER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/recycle/RECOVER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/recycle/RECOVER.md
Labels: Need update version-2.1, Need update version-3.0

#1510 [improvement] imrovement doc of auto inc column
  docs/table-design/auto-increment.md
Labels: request review

#1561 [Improvement](docs) refine query acceleration doc
  docs/query-acceleration/colocation-join.md
  docs/query-acceleration/hints/distribute-hint.md
  docs/query-acceleration/hints/hints-overview.md
  docs/query-acceleration/hints/leading-hint.md
  docs/query-acceleration/optimization-technology-principle/pipeline-execution-engine.md
  docs/query-acceleration/optimization-technology-principle/query-optimizer.md
  docs/query-acceleration/optimization-technology-principle/runtime-filter.md
  docs/query-acceleration/optimization-technology-principle/statistics.md
  docs/query-acceleration/optimization-technology-principle/topn-optimization.md
  docs/query-acceleration/performance-tuning-overview/analysis-tools.md
  docs/query-acceleration/performance-tuning-overview/diagnostic-tools.md
  docs/query-acceleration/performance-tuning-overview/tuning-overview.md
  docs/query-acceleration/performance-tuning-overview/tuning-process.md
  docs/query-acceleration/tuning/join-hint.md
  docs/query-acceleration/tuning/overview.md
  docs/query-acceleration/tuning/query-profile.md
  docs/query-acceleration/tuning/tuning-parameters.md
  docs/query-acceleration/tuning/tuning-plan/accelerating-point-query.md
  docs/query-acceleration/tuning/tuning-plan/accelerating-queries-with-runtime-filter.md
  docs/query-acceleration/tuning/tuning-plan/reordering-join-with-leading-hint.md
  docs/query-acceleration/tuning/tuning-plan/solving-unevenly-data-distribution.md
  docs/query-acceleration/tuning/tuning-plan/tuning-plan-with-statistics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/colocation-join.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/hints/distribute-hint.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/hints/hints-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/hints/leading-hint.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/pipeline-execution-engine.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/query-optimizer.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/runtime-filter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/statistics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/topn-optimization.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/analysis-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/diagnostic-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/tuning-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/tuning-process.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/query-profile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-parameters.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/accelerating-point-query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/accelerating-queries-with-runtime-filter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/accelerating-queries-with-sql-cache.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/adjusting-join-shuffle.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/controlling-hints-with-cbo-rule.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/dml-tuning-plan.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/optimizing-join-with-colocate-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/optimizing-table-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/optimizing-table-scanning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/optimizing-table-schema.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/reordering-join-with-leading-hint.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/solving-unevenly-data-distribution.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/transparent-rewriting-with-async-mv.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/transparent-rewriting-with-sync-mv.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/tuning-plan-with-statistics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v2.1/release-2.1.0.md
  sidebars.json
Labels: bug, Need update EN version, approved

#1578 [polish](MySQL-compatability) polish MySQL-compatability docs
  docs/query-data/mysql-compatibility.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/mysql-compatibility.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/mysql-compatibility.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/mysql-compatibility.md
  versioned_docs/version-2.1/query-data/mysql-compatibility.md
  versioned_docs/version-3.0/query-data/mysql-compatibility.md
Labels: approved

#1586 [Improvement](docs) refine query acceleration doc
  docs/query-acceleration/performance-tuning-overview/analysis-tools.md
  docs/query-acceleration/performance-tuning-overview/diagnostic-tools.md
  docs/query-acceleration/performance-tuning-overview/tuning-overview.md
  docs/query-acceleration/performance-tuning-overview/tuning-process.md
  docs/query-acceleration/tuning/tuning-plan/optimizing-table-index.md
  docs/query-acceleration/tuning/tuning-plan/optimizing-table-scanning.md
  docs/query-acceleration/tuning/tuning-plan/optimizing-table-schema.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/analysis-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/diagnostic-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/tuning-process.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/accelerating-queries-with-sql-cache.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/transparent-rewriting-with-sync-mv.md
Labels: Need update version-2.1, Need update version-3.0

#1450 [refactor](ecosystem) refactor flink doris connector doc
  docs/ecosystem/flink-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/flink-doris-connector.md
Labels: request review, has comments

#1527 [doc] update arrow-flight-sql-connect.md markdown format
  i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md
Labels: approved

#1526 [doc](group-commit) Optimize the document of group commit
  docs/data-operate/import/group-commit-manual.md
  docs/data-operate/import/import-way/insert-into-values-manual.md
  docs/data-operate/import/load-manual.md
  docs/data-operate/transaction.md
  docs/releasenotes/v2.1/release-2.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/group-commit-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/transaction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/group-commit-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/transaction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/group-commit-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/transaction.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/group-commit-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
  versioned_docs/version-2.1/data-operate/import/load-manual.md
  versioned_docs/version-2.1/data-operate/transaction.md
  versioned_docs/version-2.1/releasenotes/v2.1/release-2.1.0.md
  versioned_docs/version-3.0/data-operate/import/group-commit-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
  versioned_docs/version-3.0/data-operate/import/load-manual.md
  versioned_docs/version-3.0/data-operate/transaction.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1582 Column compression master
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/column-compression.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/column-compression.md
  versioned_docs/version-2.1/table-design/column-compression.md
  versioned_docs/version-3.0/table-design/column-compression.md
Labels: approved

#1559 [opt] Modify storage vault `use_path_style` default behavior
  docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
Labels: approved

#1558 [doc] add query-acceleration in query engine docs
  docs/query-acceleration/distinct-counts/bitmap-precise-deduplication.md
  docs/query-acceleration/distinct-counts/hll-approximate-deduplication.md
  docs/query-acceleration/distinct-counts/orthogonal-bitmap-manual.md
  docs/query-acceleration/distinct-counts/using-hll.md
  docs/query-acceleration/tuning/parallelism-tuning.md
  docs/query-acceleration/tuning/tuning-execution/adjustment-of-runtimefilter-wait-time.md
  docs/query-acceleration/tuning/tuning-execution/data-skew-handling.md
  docs/query-acceleration/tuning/tuning-execution/parallelism-adjustment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/distinct-counts/bitmap-precise-deduplication.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/distinct-counts/hll-approximate-deduplication.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/distinct-counts/orthogonal-bitmap-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/distinct-counts/using-hll.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/analysis-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/tuning-process.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/parallelism-tuning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-execution/adjustment-of-runtimefilter-wait-time.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-execution/data-skew-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-execution/parallelism-adjustment.md
  sidebars.json
Labels: approved

#1542 update getting-started
  docs/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/what-is-apache-doris.md
  static/images/getting-started/apache-doris-query-engine-1.png
  static/images/getting-started/apache-doris-query-engine-2.png
  static/images/getting-started/apache-doris-technical-compute-storage-decouple-overview.png
  static/images/getting-started/apache-doris-technical-overview.png
  static/images/getting-started/apache-doris-usage-scenarios-pipeline.png
  versioned_docs/version-1.2/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-2.0/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-2.1/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-3.0/gettingStarted/what-is-apache-doris.md
Labels: approved

#1594 [fix] add data-distribution for 3.0 and 2.1
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/data-distribution.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/data-distribution.md
  versioned_docs/version-2.1/table-design/data-partitioning/data-distribution.md
  versioned_docs/version-3.0/table-design/data-partitioning/data-distribution.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1595 [fix] auto inc opt to 3.0 and 2.1
  docs/table-design/auto-increment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/auto-increment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/auto-increment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/auto-increment.md
  versioned_docs/version-2.1/table-design/auto-increment.md
  versioned_docs/version-3.0/table-design/auto-increment.md
Labels: Reviewed

#1609 [fix] Business continuity & data recovery directory name in zh
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
Labels: approved

#1608 [fix] fix some typos
  docs/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-1.2/releasenotes/v3.0/release-3.0.0.md
  versioned_docs/version-2.0/releasenotes/v3.0/release-3.0.0.md
  versioned_docs/version-2.1/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-2.1/releasenotes/v3.0/release-3.0.0.md
  versioned_docs/version-3.0/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-3.0/releasenotes/v3.0/release-3.0.0.md
Labels: approved

#1511 [docs](load) add data source docs
  docs/data-operate/import/data-source/aliyun-oss.md
  docs/data-operate/import/data-source/amazon-s3.md
  docs/data-operate/import/data-source/azure-storage.md
  docs/data-operate/import/data-source/google-cloud-storage.md
  docs/data-operate/import/data-source/hdfs.md
  docs/data-operate/import/data-source/huawei-obs.md
  docs/data-operate/import/data-source/minio.md
  docs/data-operate/import/data-source/s3-compatible.md
  docs/data-operate/import/data-source/tencent-cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/aliyun-oss.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/amazon-s3.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/azure-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/google-cloud-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/hdfs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/huawei-obs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/minio.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/s3-compatible.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/tencent-cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/aliyun-oss.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/amazon-s3.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/google-cloud-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/hdfs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/huawei-obs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/minio.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/s3-compatible.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/tencent-cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/aliyun-oss.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/amazon-s3.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/azure-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/google-cloud-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/hdfs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/huawei-obs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/minio.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/s3-compatible.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/tencent-cos.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/data-source/aliyun-oss.md
  versioned_docs/version-2.1/data-operate/import/data-source/amazon-s3.md
  versioned_docs/version-2.1/data-operate/import/data-source/google-cloud-storage.md
  versioned_docs/version-2.1/data-operate/import/data-source/hdfs.md
  versioned_docs/version-2.1/data-operate/import/data-source/huawei-obs.md
  versioned_docs/version-2.1/data-operate/import/data-source/minio.md
  versioned_docs/version-2.1/data-operate/import/data-source/s3-compatible.md
  versioned_docs/version-2.1/data-operate/import/data-source/tencent-cos.md
  versioned_docs/version-3.0/data-operate/import/data-source/aliyun-oss.md
  versioned_docs/version-3.0/data-operate/import/data-source/amazon-s3.md
  versioned_docs/version-3.0/data-operate/import/data-source/azure-storage.md
  versioned_docs/version-3.0/data-operate/import/data-source/google-cloud-storage.md
  versioned_docs/version-3.0/data-operate/import/data-source/hdfs.md
  versioned_docs/version-3.0/data-operate/import/data-source/huawei-obs.md
  versioned_docs/version-3.0/data-operate/import/data-source/minio.md
  versioned_docs/version-3.0/data-operate/import/data-source/s3-compatible.md
  versioned_docs/version-3.0/data-operate/import/data-source/tencent-cos.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: Reviewed

#1614 [docs] Update explain and fix bug
  docs/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/EXPLAIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/before-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/EXPLAIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/data-admin/ccr.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-query/EXPLAIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/before-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-query/EXPLAIN.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-statements/data-query/EXPLAIN.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-query/EXPLAIN.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved, Reviewed

#1593 [typo](doc) fix typo
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/compilation-and-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
Labels: approved

#1543 Update Installation
  docs/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  docs/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  docs/install/preparation/cluster-planning.md
  docs/install/preparation/env-checking.md
  docs/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/cluster-planning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/cluster-planning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/cluster-planning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/os-checking.md
  sidebars.json
  versioned_docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  versioned_docs/version-2.1/install/preparation/cluster-planning.md
  versioned_docs/version-2.1/install/preparation/env-checking.md
  versioned_docs/version-2.1/install/preparation/os-checking.md
  versioned_docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  versioned_docs/version-3.0/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  versioned_docs/version-3.0/install/preparation/cluster-planning.md
  versioned_docs/version-3.0/install/preparation/env-checking.md
  versioned_docs/version-3.0/install/preparation/os-checking.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: Need update version-2.1, Need update version-3.0

#1548 [doc](load) refactor load doc
  docs/data-operate/import/complex-types/bitmap.md
  docs/data-operate/import/complex-types/hll.md
  docs/data-operate/import/complex-types/variant.md
  docs/data-operate/import/data-source/kafka.md
  docs/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/bitmap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/hll.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/variant.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/bitmap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/hll.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/variant.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/azure-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/bitmap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/hll.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/variant.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/local-file.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/complex-types/bitmap.md
  versioned_docs/version-2.1/data-operate/import/complex-types/hll.md
  versioned_docs/version-2.1/data-operate/import/complex-types/variant.md
  versioned_docs/version-2.1/data-operate/import/data-source/azure-storage.md
  versioned_docs/version-2.1/data-operate/import/data-source/kafka.md
  versioned_docs/version-2.1/data-operate/import/data-source/local-file.md
  versioned_docs/version-3.0/data-operate/import/complex-types/bitmap.md
  versioned_docs/version-3.0/data-operate/import/complex-types/hll.md
  versioned_docs/version-3.0/data-operate/import/complex-types/variant.md
  versioned_docs/version-3.0/data-operate/import/data-source/kafka.md
  versioned_docs/version-3.0/data-operate/import/data-source/local-file.md
Labels: Reviewed

#1587 [improve](docs) fix and improve insert into manual
  docs/data-operate/import/import-way/insert-into-manual.md
  docs/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
Labels: has comments

#1521 [docs](load) add data type docs
  docs/data-operate/import/complex-types/array.md
  docs/data-operate/import/complex-types/json.md
  docs/data-operate/import/complex-types/map.md
  docs/data-operate/import/complex-types/struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/json.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/json.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/json.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/struct.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/complex-types/array.md
  versioned_docs/version-2.1/data-operate/import/complex-types/json.md
  versioned_docs/version-2.1/data-operate/import/complex-types/map.md
  versioned_docs/version-2.1/data-operate/import/complex-types/struct.md
  versioned_docs/version-3.0/data-operate/import/complex-types/array.md
  versioned_docs/version-3.0/data-operate/import/complex-types/json.md
  versioned_docs/version-3.0/data-operate/import/complex-types/map.md
  versioned_docs/version-3.0/data-operate/import/complex-types/struct.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: Reviewed

#1508 [cloud] update compute group doc
  docs/compute-storage-decoupled/managing-compute-cluster.md
  docs/compute-storage-decoupled/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-compute-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-compute-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/overview.md
  versioned_docs/version-3.0/compute-storage-decoupled/managing-compute-cluster.md
  versioned_docs/version-3.0/compute-storage-decoupled/overview.md
Labels: bug, Reviewed

#1642 [Doc](refactor)update sequence
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
  sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1629 update sidebar for import, update and export
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1603 [fix] make create table and load data procedure easily
  docs/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/window-function.md
  versioned_docs/version-2.1/query-data/window-function.md
  versioned_docs/version-3.0/query-data/window-function.md
Labels: request review

#1630 Fix http url error
  docs/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
  docs/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
  docs/admin-manual/memory-management/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/memory-management/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/memory-management/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/memory-management/overview.md
  versioned_docs/version-2.1/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
  versioned_docs/version-2.1/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
  versioned_docs/version-2.1/admin-manual/memory-management/overview.md
  versioned_docs/version-3.0/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
  versioned_docs/version-3.0/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
  versioned_docs/version-3.0/admin-manual/memory-management/overview.md
Labels: approved

#1638 update Installation - delete socket checking
  docs/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/os-checking.md
  versioned_docs/version-2.1/install/preparation/os-checking.md
  versioned_docs/version-3.0/install/preparation/os-checking.md
Labels: approved

#1473 [doc](mtmv) Async materialized view doc optimize
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/use-guide.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md
Labels: Need update EN version, Need update version-2.1, Need update version-3.0

#1649 refine compute group en docs
  docs/admin-manual/workload-management/compute-group.md
  versioned_docs/version-3.0/admin-manual/workload-management/compute-group.md
Labels: request review

#1600 [doc](load) optimize handling messy data
  docs/data-operate/import/error-data-handling.md
  docs/data-operate/import/handling-messy-data.md
  docs/data-operate/import/import-way/routine-load-manual.md
  docs/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/error-data-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/handling-messy-data.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/error-data-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/handling-messy-data.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/error-data-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/handling-messy-data.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/error-data-handling.md
  versioned_docs/version-2.1/data-operate/import/handling-messy-data.md
  versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-3.0/data-operate/import/error-data-handling.md
  versioned_docs/version-3.0/data-operate/import/handling-messy-data.md
  versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review

#1574 [opt](backup) optimize backup doc
  docs/admin-manual/data-admin/backup-restore/backup.md
  docs/admin-manual/data-admin/backup-restore/overview.md
  docs/admin-manual/data-admin/backup-restore/restore.md
  docs/admin-manual/data-admin/data-recovery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/backup-restore/backup.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/backup-restore/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/backup-restore/restore.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/backup-restore/backup.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/backup-restore/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/backup-restore/restore.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/backup-restore/backup.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/backup-restore/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/backup-restore/restore.md
  sidebars.json
  versioned_docs/version-2.1/admin-manual/data-admin/backup-restore/backup.md
  versioned_docs/version-2.1/admin-manual/data-admin/backup-restore/overview.md
  versioned_docs/version-2.1/admin-manual/data-admin/backup-restore/restore.md
  versioned_docs/version-3.0/admin-manual/data-admin/backup-restore/backup.md
  versioned_docs/version-3.0/admin-manual/data-admin/backup-restore/overview.md
  versioned_docs/version-3.0/admin-manual/data-admin/backup-restore/restore.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: has comments, Need update version-2.1, Need update version-dev

#1669 [Improvement](docs) refine query acceleration doc
  docs/query-acceleration/performance-tuning-overview/analysis-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/hints/hints-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/analysis-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/hints/hints-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/performance-tuning-overview/analysis-tools.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/hints/hints-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/performance-tuning-overview/analysis-tools.md
  versioned_docs/version-2.1/query-acceleration/performance-tuning-overview/analysis-tools.md
  versioned_docs/version-3.0/query-acceleration/performance-tuning-overview/analysis-tools.md
Labels: approved

#1671 [doc](mtmv) Optimize sync and async mv doc
  docs/query-acceleration/materialized-view/async-materialized-view/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/use-guide.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/sync-materialized-view.md
Labels: Need update version-2.1, Need update version-3.0

#1635 [doc](load) optimize load transform
  docs/data-operate/import/load-data-convert.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-convert.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-convert.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-convert.md
  versioned_docs/version-2.1/data-operate/import/load-data-convert.md
  versioned_docs/version-3.0/data-operate/import/load-data-convert.md
Labels: request review

#1647 update unsubscribe mail list
  community/subscribe-mail-list.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/subscribe-mail-list.md
Labels: bug

#1664 update elastic-expansion
  docs/admin-manual/cluster-management/elastic-expansion.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/cluster-management/elastic-expansion.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/cluster-management/elastic-expansion.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/cluster-management/elastic-expansion.md
  versioned_docs/version-2.1/admin-manual/cluster-management/elastic-expansion.md
  versioned_docs/version-3.0/admin-manual/cluster-management/elastic-expansion.md
Labels: has comments

#1437 update index docs structure
  docs/table-design/index/bloomfilter.md
  docs/table-design/index/inverted-index.md
  docs/table-design/index/ngram-bloomfilter-index.md
  docs/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/bloomfilter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/bloomfilter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/bloomfilter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/bloomfilter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/prefix-index.md
  versioned_docs/version-2.0/table-design/index/bloomfilter.md
  versioned_docs/version-2.0/table-design/index/inverted-index.md
  versioned_docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-2.0/table-design/index/prefix-index.md
  versioned_docs/version-2.1/table-design/index/bloomfilter.md
  versioned_docs/version-2.1/table-design/index/inverted-index.md
  versioned_docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-2.1/table-design/index/prefix-index.md
  versioned_docs/version-3.0/table-design/index/bloomfilter.md
  versioned_docs/version-3.0/table-design/index/inverted-index.md
  versioned_docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-3.0/table-design/index/prefix-index.md
Labels: has comments, Need update EN version, Need update version-2.1, Need update version-3.0
