Repository apache/doris-website, pull requests merged in 2024-10, with the labels that each got.

#1168 [release] Update 2.0.15 release
  blog/release-note-2.0.15.md
  common_docs_zh/gettingStarted/demo-block/latest.tsx
  common_docs_zh/releasenotes/all-release.md
  common_docs_zh/releasenotes/v2.0/release-2.0.15.md
  gettingStarted/demo-block/latest.tsx
  releasenotes/all-release.md
  releasenotes/v2.0/release-2.0.15.md
  sidebars.json
  src/constant/download.data.ts
  src/constant/newsletter.data.ts
  static/images/2.0.15.jpg
  versioned_sidebars/version-1.2-sidebars.json
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: version-2.0, Reviewed

#1072 [improve](cloud-deploy) add docs for deploying doris cloud
  docs/admin-manual/config/be-config.md
  docs/admin-manual/config/fe-config.md
  docs/compute-storage-decoupled/before-deployment.md
  docs/compute-storage-decoupled/compilation-and-deployment.md
  docs/compute-storage-decoupled/creating-cluster.md
  docs/compute-storage-decoupled/file-cache.md
  docs/compute-storage-decoupled/managing-compute-cluster.md
  docs/compute-storage-decoupled/managing-storage-vault.md
  docs/compute-storage-decoupled/overview.md
  docs/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
  docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/sql-manual/sql-statements/Database-Administration-Statements/WARM-UP-COMPUTE-GROUP.md
  docs/sql-manual/sql-statements/Show-Statements/SHOW-CACHE-HOTSPOT.md
  docs/sql-manual/sql-statements/Show-Statements/SHOW-WARM-UP-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/before-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/compilation-and-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/creating-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/file-cache.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-compute-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-storage-vault.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Database-Administration-Statements/WARM-UP-COMPUTE-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-CACHE-HOTSPOT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-WARM-UP-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/before-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/creating-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/file-cache.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-compute-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Database-Administration-Statements/WARM-UP-COMPUTE-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Show-Statements/SHOW-CACHE-HOTSPOT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Show-Statements/SHOW-WARM-UP-JOB.md
  sidebars.json
  versioned_docs/version-2.0/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
  versioned_docs/version-2.1/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
  versioned_docs/version-3.0/admin-manual/config/be-config.md
  versioned_docs/version-3.0/admin-manual/config/fe-config.md
  versioned_docs/version-3.0/compute-storage-decoupled/before-deployment.md
  versioned_docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
  versioned_docs/version-3.0/compute-storage-decoupled/creating-cluster.md
  versioned_docs/version-3.0/compute-storage-decoupled/file-cache.md
  versioned_docs/version-3.0/compute-storage-decoupled/managing-compute-cluster.md
  versioned_docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
  versioned_docs/version-3.0/compute-storage-decoupled/overview.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-ADD-BACKEND.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Database-Administration-Statements/WARM-UP-COMPUTE-GROUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Show-Statements/SHOW-CACHE-HOTSPOT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Show-Statements/SHOW-WARM-UP-JOB.md
  versioned_sidebars/version-3.0-sidebars.json
Labels: Dont merge

#1175 [feature](jdbc catalog) add gbase 8a jdbc catalog docs
  docs/lakehouse/database/gbase-8a.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/gbase-8a.md
  sidebars.json
Labels: version-dev, Reviewed

#1176 update the config of max_batch_rows and max_batch_size
  docs/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  versioned_docs/version-2.0/data-operate/import/routine-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
Labels: version-2.1, version-dev, version-2.0, Reviewed, version-3.0

#1177 [fix](typo) fix typo in compute and storage decoupled
  docs/compute-storage-decoupled/compilation-and-deployment.md
  versioned_docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
Labels: version-dev, Reviewed, version-3.0

#1184 [events] Update singapore events
  docusaurus.config.js
  gettingStarted/demo-block/latest.tsx
Labels: Reviewed

#1130 [fix](docs) correct the incorrect version requirements for DB2 synchronization.
  common_docs_zh/ecosystem/flink-doris-connector.md
  ecosystem/flink-doris-connector.md
Labels: version-2.1, version-dev, version-2.0, Reviewed, version-3.0

#1188 [events] Update events link
  docusaurus.config.js
  gettingStarted/demo-block/latest.tsx
Labels: Reviewed

#1190 [fix](release) Fix 2.0.15 release note
  blog/release-note-2.0.15.md
  common_docs_zh/releasenotes/v2.0/release-2.0.15.md
  releasenotes/v2.0/release-2.0.15.md
Labels: version-2.0, Reviewed

#1174 [doc](cloud-deploy) add an example for CREATE-STORAGE-VAULT
  docs/compute-storage-decoupled/before-deployment.md
  docs/compute-storage-decoupled/compilation-and-deployment.md
  docs/compute-storage-decoupled/managing-storage-vault.md
  docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/before-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-storage-vault.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/before-deployment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
  versioned_docs/version-3.0/compute-storage-decoupled/before-deployment.md
  versioned_docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
  versioned_docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
Labels: version-dev, version-3.0

#907 add crc32 docs
  docs/sql-manual/sql-functions/string-functions/crc32.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/crc32.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/string-functions/crc32.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/string-functions/crc32.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/string-functions/crc32.md
  versioned_docs/version-3.0/sql-manual/sql-functions/string-functions/crc32.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1172 profile_manager_gc_interval_seconds
  docs/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md
  versioned_docs/version-3.0/admin-manual/config/fe-config.md
Labels: version-dev, Reviewed, version-3.0

#1173 session vars used to control scanner
  docs/query/query-variables/variables.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-variables/variables.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/query-variables/variables.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query/query-variables/variables.md
  versioned_docs/version-2.1/query/query-variables/variables.md
  versioned_docs/version-3.0/query/query-variables/variables.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1189 [doc] Add type of SET for BitmapValue
  community/developer-guide/bitmap-hll-file-format.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/bitmap-hll-file-format.md
Labels: Reviewed

#1199 fix: fix announcementBar id error
  docusaurus.config.js
Labels: Reviewed

#1197 Fix routine load doc mistake and adjust doc structure
  docs/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-2.0/data-operate/import/routine-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
Labels: version-2.1, version-dev, version-2.0, Reviewed, version-3.0

#1170 [ecosystem]Kafka-connector properties adds timeout adjustment suggestions
  common_docs_zh/ecosystem/doris-kafka-connector.md
  ecosystem/doris-kafka-connector.md
Labels: version-2.1, version-dev, version-2.0, Reviewed, version-3.0

#1195 [docs](delete) Update delete timeout related docs
  docs/data-operate/delete/delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/delete-manual.md
  versioned_docs/version-2.1/data-operate/delete/delete-manual.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1198 [fix]modify error description of Request and Examples
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/be-http/check-tablet-segment.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1208 [fix](install) Fix typo of install docs
  docusaurus.config.js
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-env.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-operator.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/run-docker-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/standard-deployment.md
Labels: Reviewed

#1209 [release] Fix EN 3.0.0 release pics
  blog/release-note-3.0.0.md
  common_docs_zh/releasenotes/v2.0/release-2.0.0.md
  common_docs_zh/releasenotes/v2.1/release-2.1.0.md
  releasenotes/v2.1/release-2.1.0.md
  releasenotes/v3.0/release-3.0.0.md
  static/images/blind-test-performance-improvement.png
  static/images/comparison-with-alternative-solutions.png
  static/images/design-hightlight.PNG
  static/images/query-performance-comparison.png
  static/images/real-time-write-performance..png
  static/images/write-speed-comparison.png
Labels: Reviewed

#1215 [docs](install) Fix typo and update download link
  common_docs_zh/releasenotes/v2.1/release-2.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-doris-cluster.md
  src/constant/download.data.ts
Labels: version-2.1, Reviewed

#1220 [event] Update doris meetup
  common_docs_zh/gettingStarted/demo-block/latest.tsx
  docusaurus.config.js
Labels: Reviewed

#1216 [Chore] Update flink connector version
  common_docs_zh/ecosystem/flink-doris-connector.md
  ecosystem/flink-doris-connector.md
Labels: Reviewed

#1221 feat: fix streamloader download error
  src/components/download-form/download-form-tools.tsx
  src/constant/download.data.ts
  src/theme/DocVersionBanner/index.js
Labels: Reviewed

#1213 [fix] Modify the incorrect description of the returned field content
  docs/admin-manual/open-api/be-http/health.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/health.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/be-http/health.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/open-api/be-http/health.md
  versioned_docs/version-2.1/admin-manual/open-api/be-http/health.md
  versioned_docs/version-3.0/admin-manual/open-api/be-http/health.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1205 [fix](doc) add partitions now only support 3.0
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/data-partition.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partition.md
  versioned_docs/version-2.0/table-design/data-partition.md
  versioned_docs/version-2.1/table-design/data-partition.md
Labels: version-2.1, version-2.0, Reviewed

#1214 [doc](function)support bit_test function
  docs/sql-manual/sql-functions/bitwise-functions/bit_test.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/bitwise-functions/bit_test.md
  sidebars.json
Labels: version-dev, Reviewed

#1211 [doc](function)support count_substrings functions
  docs/sql-manual/sql-functions/string-functions/count_substrings.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/count_substrings.md
  sidebars.json
Labels: version-dev, Reviewed

#1224 [docs](systemTable) Fix typo of system table
  docs/admin-manual/system-tables/information_schema/columns.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/overview.md
  versioned_docs/version-2.1/admin-manual/system-tables/information_schema/columns.md
  versioned_docs/version-3.0/admin-manual/system-tables/information_schema/columns.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1182 [doc](tiered) Add dynamic partition migration Pick #874 to 2.1 and 3.0
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partition.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/diff-disk-medium-migration.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/remote-storage.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partition.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/diff-disk-medium-migration.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.md
  versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  versioned_docs/version-2.1/table-design/data-partition.md
  versioned_docs/version-2.1/table-design/tiered-storage/diff-disk-medium-migration.md
  versioned_docs/version-2.1/table-design/tiered-storage/remote-storage.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  versioned_docs/version-3.0/table-design/data-partition.md
  versioned_docs/version-3.0/table-design/tiered-storage/diff-disk-medium-migration.md
  versioned_docs/version-3.0/table-design/tiered-storage/remote-storage.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: version-2.1, version-3.0

#1140 [Docs] Add doc for flexible partial update
  docs/data-operate/import/import-way/stream-load-manual.md
  docs/data-operate/update/update-of-unique-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-unique-model.md
Labels: dependencies

#1234 [doc](stream_load)fix_stream_load2pc_doc
  docs/data-operate/transaction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/transaction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/transaction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/transaction.md
  versioned_docs/version-2.1/data-operate/transaction.md
  versioned_docs/version-3.0/data-operate/transaction.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1111 [doc](flink) update flink connector faq
  common_docs_zh/ecosystem/flink-doris-connector.md
  ecosystem/flink-doris-connector.md
Labels: version-2.1, version-dev, version-2.0, version-3.0

#1237 [documents]add grouping workload groups document
  docs/admin-manual/resource-admin/group-workload-groups.md
  docs/admin-manual/resource-admin/workload-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/group-workload-groups.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/workload-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/group-workload-groups.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-group.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/resource-admin/group-workload-groups.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/resource-admin/workload-group.md
  sidebars.json
  static/images/workload-management/group_wg_add_be.png
  static/images/workload-management/group_wg_add_cluster.png
  static/images/workload-management/group_wg_default.png
  static/images/workload-management/group_wg_two_group.png
  static/images/workload-management/rg1_rg2_workload_group.png
  versioned_docs/version-2.1/admin-manual/resource-admin/group-workload-groups.md
  versioned_docs/version-2.1/admin-manual/resource-admin/workload-group.md
  versioned_docs/version-3.0/admin-manual/resource-admin/group-workload-groups.md
  versioned_docs/version-3.0/admin-manual/resource-admin/workload-group.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: version-2.1, version-dev, version-3.0

#1240 [doc](typo) fix some typo in table-design section
  docs/table-design/auto-increment.md
  docs/table-design/index/inverted-index.md
  docs/table-design/index/ngram-bloomfilter-index.md
  docs/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/auto-increment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/data-table/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/auto-increment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/auto-increment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/prefix-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/schema-change.md
  versioned_docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-2.0/table-design/schema-change.md
  versioned_docs/version-2.1/table-design/auto-increment.md
  versioned_docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-2.1/table-design/schema-change.md
  versioned_docs/version-3.0/table-design/auto-increment.md
  versioned_docs/version-3.0/table-design/index/inverted-index.md
  versioned_docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-3.0/table-design/schema-change.md
Labels: version-2.1, version-dev, version-2.0, Reviewed, version-3.0

#1238 [fix](load) fix typos in load docs
  docs/data-operate/import/error-data-handling.md
  docs/data-operate/import/import-way/broker-load-manual.md
  docs/data-operate/import/import-way/stream-load-manual.md
  docs/data-operate/import/load-data-format.md
  docs/lakehouse/datalake-analytics/hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/error-data-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-format.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/data-operate/import/import-scenes/external-storage-load.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/data-operate/import/import-way/s3-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/error-data-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-format.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/error-data-handling.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-format.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Load/BROKER-LOAD.md
  versioned_docs/version-1.2/data-operate/import/import-scenes/external-storage-load.md
  versioned_docs/version-1.2/data-operate/import/import-way/s3-load-manual.md
  versioned_docs/version-2.0/data-operate/import/broker-load-manual.md
  versioned_docs/version-2.0/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-2.1/data-operate/import/error-data-handling.md
  versioned_docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
  versioned_docs/version-2.1/data-operate/import/load-data-format.md
  versioned_docs/version-2.1/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-3.0/data-operate/import/error-data-handling.md
  versioned_docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
  versioned_docs/version-3.0/data-operate/import/load-data-format.md
  versioned_docs/version-3.0/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Load/BROKER-LOAD.md
Labels: bug, version-2.1, version-dev, version-2.0, version-3.0

#1241 [Doc](flink) add arrow flight sql read doc
  common_docs_zh/ecosystem/flink-doris-connector.md
  ecosystem/flink-doris-connector.md
Labels: version-dev

#1200 [fix](docs) Correct the parameter configuration errors in the Flink connector documentation
  common_docs_zh/ecosystem/flink-doris-connector.md
  ecosystem/flink-doris-connector.md
Labels: Reviewed

#936 [Feature](insert-overwrite) Support create partition for auto partition table when insert overwrite
  docs/query/query-variables/variables.md
  docs/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-variables/variables.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/delete-query-variables/variables.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query/query-variables/variables.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
  versioned_docs/version-2.1/query-data/delete-query-variables/variables.md
  versioned_docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
  versioned_docs/version-3.0/query/query-variables/variables.md
  versioned_docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1148 [doc] hour/minute/second functions support time as an argument.
  docs/sql-manual/sql-functions/date-time-functions/hour.md
  docs/sql-manual/sql-functions/date-time-functions/minute.md
  docs/sql-manual/sql-functions/date-time-functions/second.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/hour.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/minute.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/second.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/hour.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/minute.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/second.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/hour.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/minute.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/second.md
  versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/hour.md
  versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/minute.md
  versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/second.md
  versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/hour.md
  versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/minute.md
  versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/second.md
Labels: version-2.1, version-dev, Reviewed, version-3.0

#1236 [doc](routine load) update routine load doc about max_batch_interval and fix some error
  docs/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-2.0/data-operate/import/routine-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
Labels: version-2.1, version-dev, version-2.0, Reviewed, version-3.0

#1239 [update] Update web info
  common_docs_zh/ecosystem/cloudcanal.md
  common_docs_zh/gettingStarted/demo-block/latest.tsx
  ecosystem/cloudcanal.md
  gettingStarted/demo-block/latest.tsx
  sidebars.json
  src/components/achievement-banner/achievement-banner.data.ts
  src/components/achievement-banner/achievement-banner.scss
  versioned_sidebars/version-1.2-sidebars.json
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: Reviewed

#1217 [Fix](CI) make file move related deadlink check enable
  .github/workflows/build-check.yml
Labels: Reviewed

#1255 [Fix](function) Add highlight reminder for function sleep
  docs/sql-manual/sql-functions/debug-functions/sleep.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/debug-functions/sleep.md
Labels: version-dev, Reviewed
