Repository apache/doris-website, pull requests merged in 2025-02, with the labels that each got.

#1903 [doc]modify catalog docs
  docs/sql-manual/sql-statements/catalog/ALTER-CATALOG.md
  docs/sql-manual/sql-statements/catalog/CREATE-CATALOG.md
  docs/sql-manual/sql-statements/catalog/DROP-CATALOG.md
  docs/sql-manual/sql-statements/catalog/REFRESH.md
  docs/sql-manual/sql-statements/catalog/SHOW-CATALOG.md
  docs/sql-manual/sql-statements/catalog/SHOW-CREATE-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/catalog/ALTER-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/catalog/CREATE-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/catalog/DROP-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/catalog/REFRESH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/catalog/SHOW-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/catalog/SHOW-CREATE-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/catalog/ALTER-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/catalog/CREATE-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/catalog/DROP-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/catalog/REFRESH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/catalog/SHOW-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/catalog/SHOW-CREATE-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/catalog/ALTER-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/catalog/CREATE-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/catalog/DROP-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/catalog/REFRESH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/catalog/SHOW-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/catalog/SHOW-CREATE-CATALOG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/catalog/ALTER-CATALOG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/catalog/CREATE-CATALOG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/catalog/DROP-CATALOG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/catalog/REFRESH.md
  versioned_docs/version-2.1/sql-manual/sql-statements/catalog/SHOW-CATALOG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/catalog/SHOW-CREATE-CATALOG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/catalog/ALTER-CATALOG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/catalog/CREATE-CATALOG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/catalog/DROP-CATALOG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/catalog/REFRESH.md
  versioned_docs/version-3.0/sql-manual/sql-statements/catalog/SHOW-CATALOG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/catalog/SHOW-CREATE-CATALOG.md
Labels: has comments

#1911 [Doc] Fix plugin related documentation
  docs/sql-manual/sql-statements/plugin/INSTALL-PLUGIN.md
  docs/sql-manual/sql-statements/plugin/SHOW-PLUGINS.md
  docs/sql-manual/sql-statements/plugin/UNINSTALL-PLUGIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/plugin/INSTALL-PLUGIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/plugin/SHOW-PLUGINS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/plugin/UNINSTALL-PLUGIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/plugin/INSTALL-PLUGIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/plugin/SHOW-PLUGINS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/plugin/UNINSTALL-PLUGIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/plugin/INSTALL-PLUGIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/plugin/SHOW-PLUGINS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/plugin/UNINSTALL-PLUGIN.md
  versioned_docs/version-2.1/sql-manual/sql-statements/plugin/INSTALL-PLUGIN.md
  versioned_docs/version-2.1/sql-manual/sql-statements/plugin/SHOW-PLUGINS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/plugin/UNINSTALL-PLUGIN.md
  versioned_docs/version-3.0/sql-manual/sql-statements/plugin/INSTALL-PLUGIN.md
  versioned_docs/version-3.0/sql-manual/sql-statements/plugin/SHOW-PLUGINS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/plugin/UNINSTALL-PLUGIN.md
Labels: has comments

#1927 [Doc] Fix database related documentation
  docs/sql-manual/sql-statements/database/ALTER-DATABASE.md
  docs/sql-manual/sql-statements/database/CREATE-DATABASE.md
  docs/sql-manual/sql-statements/database/DROP-DATABASE.md
  docs/sql-manual/sql-statements/database/SHOW-CREATE-DATABASE.md
  docs/sql-manual/sql-statements/database/SHOW-DATABASE-ID.md
  docs/sql-manual/sql-statements/database/SHOW-DATABASES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/ALTER-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/DROP-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/SHOW-CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/SHOW-DATABASE-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/SHOW-DATABASES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/database/ALTER-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/database/CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/database/DROP-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/database/SHOW-CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/database/SHOW-DATABASE-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/database/SHOW-DATABASES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/ALTER-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/DROP-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/SHOW-CREATE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/SHOW-DATABASE-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/SHOW-DATABASES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/database/ALTER-DATABASE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/database/CREATE-DATABASE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/database/DROP-DATABASE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/database/SHOW-CREATE-DATABASE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/database/SHOW-DATABASE-ID.md
  versioned_docs/version-2.1/sql-manual/sql-statements/database/SHOW-DATABASES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/database/ALTER-DATABASE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/database/CREATE-DATABASE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/database/DROP-DATABASE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/database/SHOW-CREATE-DATABASE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/database/SHOW-DATABASE-ID.md
  versioned_docs/version-3.0/sql-manual/sql-statements/database/SHOW-DATABASES.md
Labels: has comments

#1815 add docs k8s operator deploy on cloud platform
  docs/ecosystem/doris-operator/doris-operator-overview.md
  docs/ecosystem/doris-operator/on-alibaba.md
  docs/ecosystem/doris-operator/on-aws.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-operator/doris-operator-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-operator/on-alibaba.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-operator/on-aws.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-operator/doris-operator-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-operator/on-alibaba.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-operator/on-aws.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-operator/doris-operator-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-operator/on-alibaba.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-operator/on-aws.md
  sidebars.json
  versioned_docs/version-2.1/ecosystem/doris-operator/doris-operator-overview.md
  versioned_docs/version-2.1/ecosystem/doris-operator/on-alibaba.md
  versioned_docs/version-2.1/ecosystem/doris-operator/on-aws.md
  versioned_docs/version-3.0/ecosystem/doris-operator/doris-operator-overview.md
  versioned_docs/version-3.0/ecosystem/doris-operator/on-alibaba.md
  versioned_docs/version-3.0/ecosystem/doris-operator/on-aws.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: has comments

#1940 [Doc]modify pmod radians random
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/pmod.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/radians.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/random.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/pmod.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/radians.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/random.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/pmod.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/radians.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/random.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/pmod.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/radians.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/random.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/pmod.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/radians.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/random.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/pmod.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/radians.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/random.md
Labels: approved

#1909 [doc](fix) statement-dev
  docs/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-EXPORT.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/CLEAN-LABEL.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/EXPORT.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  docs/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
  docs/sql-manual/sql-statements/table-and-view/index/SHOW-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/CLEAN-LABEL.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/index/SHOW-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/CLEAN-LABEL.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/index/SHOW-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/CLEAN-LABEL.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/index/SHOW-INDEX.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-EXPORT.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/CLEAN-LABEL.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/EXPORT.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/index/SHOW-INDEX.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-EXPORT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/CLEAN-LABEL.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/EXPORT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/index/SHOW-INDEX.md
Labels: request review, has comments

#1930 [doc] fix some sql statements doc
  docs/sql-manual/sql-statements/account-management/ALTER-ROLE.md
  docs/sql-manual/sql-statements/account-management/ALTER-USER.md
  docs/sql-manual/sql-statements/account-management/CREATE-ROLE.md
  docs/sql-manual/sql-statements/account-management/CREATE-USER.md
  docs/sql-manual/sql-statements/account-management/DROP-ROLE.md
  docs/sql-manual/sql-statements/account-management/DROP-USER.md
  docs/sql-manual/sql-statements/account-management/SET-PASSWORD.md
  docs/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/ALTER-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/ALTER-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/CREATE-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/CREATE-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/DROP-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/DROP-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SET-PASSWORD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/ALTER-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/ALTER-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/CREATE-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/CREATE-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/DROP-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/DROP-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SET-PASSWORD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/ALTER-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/ALTER-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/CREATE-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/CREATE-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/DROP-ROLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/DROP-USER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SET-PASSWORD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/ALTER-ROLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/ALTER-USER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/CREATE-ROLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/CREATE-USER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/DROP-ROLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/DROP-USER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SET-PASSWORD.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/ALTER-ROLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/ALTER-USER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/CREATE-ROLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/CREATE-USER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/DROP-ROLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/DROP-USER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SET-PASSWORD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-ROLES.md
Labels: has comments

#1926 [improve](docs)Improve type casting documentation clarity and example
  docs/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
  docs/sql-manual/sql-statements/types/SHOW-TYPECAST.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/types/SHOW-TYPECAST.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/types/SHOW-TYPECAST.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/types/SHOW-TYPECAST.md
  versioned_docs/version-2.1/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/types/SHOW-TYPECAST.md
  versioned_docs/version-3.0/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/types/SHOW-TYPECAST.md
Labels: approved

#1923 [doc] update view statement
  docs/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
  docs/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
Labels: approved

#1904 [doc] Refresh table_sql doc
  docs/sql-manual/sql-statements/table-and-view/table/ALTER-COLOCATE-GROUP.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-COLUMNS.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-DYNAMIC-PARTITION-TABLES.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/ALTER-COLOCATE-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-COLUMNS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-DYNAMIC-PARTITION-TABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/ALTER-COLOCATE-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-COLUMNS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-DYNAMIC-PARTITION-TABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/ALTER-COLOCATE-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-COLUMNS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-DYNAMIC-PARTITION-TABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITIONS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/ALTER-COLOCATE-GROUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-COLUMNS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-DYNAMIC-PARTITION-TABLES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITIONS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/ALTER-COLOCATE-GROUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-COLUMNS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-DYNAMIC-PARTITION-TABLES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITIONS.md
Labels: has comments

#1908 [docs]Fix variable docs of SHOW, SET and UNSET variables
  docs/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
  docs/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
  docs/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/variables/SET-VARIABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/variables/SHOW-VARIABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/variables/UNSET-VARIABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/variables/SET-VARIABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/variables/SHOW-VARIABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/variables/UNSET-VARIABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
Labels: approved

#1937 [doc] update fresh context statement
  docs/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
  docs/sql-manual/sql-statements/session/context/USE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/context/USE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/context/USE-DATABASE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/lakehouse-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/context/USE-DATABASE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/session/context/USE-DATABASE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/session/context/USE-DATABASE.md
Labels: approved

#1952 [doc] modified load statement
  docs/sql-manual/sql-statements/data-modification/load-and-export/BROKER-LOAD.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-LOAD.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/MYSQL-LOAD.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/SHOW-CREATE-LOAD.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-PROFILE.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-WARNINGS.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/BROKER-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/MYSQL-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/SHOW-CREATE-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-WARNINGS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/BROKER-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/MYSQL-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-CREATE-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-WARNINGS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/BROKER-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/MYSQL-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-CREATE-LOAD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-WARNINGS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/BROKER-LOAD.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-LOAD.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/MYSQL-LOAD.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-CREATE-LOAD.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-PROFILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-WARNINGS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/BROKER-LOAD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/CANCEL-LOAD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/MYSQL-LOAD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-CREATE-LOAD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-PROFILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD-WARNINGS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-LOAD.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1944 [improve](docs)Enhance documentation for file management and encryption key operations
  docs/sql-manual/sql-statements/security/CREATE-ENCRYPTKEY.md
  docs/sql-manual/sql-statements/security/CREATE-FILE.md
  docs/sql-manual/sql-statements/security/DROP-ENCRYPTKEY.md
  docs/sql-manual/sql-statements/security/DROP-FILE.md
  docs/sql-manual/sql-statements/security/SHOW-ENCRYPTKEY.md
  docs/sql-manual/sql-statements/security/SHOW-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/security/CREATE-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/security/CREATE-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/security/DROP-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/security/DROP-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/security/SHOW-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/security/SHOW-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/security/CREATE-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/security/CREATE-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/security/DROP-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/security/DROP-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/security/SHOW-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/security/SHOW-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/security/CREATE-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/security/CREATE-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/security/DROP-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/security/DROP-FILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/security/SHOW-ENCRYPTKEY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/security/SHOW-FILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/security/CREATE-ENCRYPTKEY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/security/CREATE-FILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/security/DROP-ENCRYPTKEY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/security/DROP-FILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/security/SHOW-ENCRYPTKEY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/security/SHOW-FILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/security/CREATE-ENCRYPTKEY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/security/CREATE-FILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/security/DROP-ENCRYPTKEY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/security/DROP-FILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/security/SHOW-ENCRYPTKEY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/security/SHOW-FILE.md
Labels: approved

#1976 [fix] Fix typo of What is Apache Doris
  i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/what-is-apache-doris.md
Labels: approved

#1982 [fix](docs) Fix complex types docs of en version
  docs/data-operate/import/handling-messy-data.md
  versioned_docs/version-2.1/data-operate/import/complex-types/array.md
  versioned_docs/version-2.1/data-operate/import/complex-types/json.md
  versioned_docs/version-2.1/data-operate/import/complex-types/map.md
  versioned_docs/version-2.1/data-operate/import/complex-types/struct.md
  versioned_docs/version-2.1/data-operate/import/handling-messy-data.md
  versioned_docs/version-3.0/data-operate/import/complex-types/array.md
  versioned_docs/version-3.0/data-operate/import/complex-types/json.md
  versioned_docs/version-3.0/data-operate/import/complex-types/map.md
  versioned_docs/version-3.0/data-operate/import/complex-types/struct.md
  versioned_docs/version-3.0/data-operate/import/handling-messy-data.md
Labels: approved

#1813 [doc] Modify the documentation of functions degrees dexp dfloor dlog1 dlog10
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/degrees.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/dfloor.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/dlog10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/degrees.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/dfloor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/dlog10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/math-functions/degrees.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/degrees.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/degrees.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dfloor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dlog10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/degrees.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dfloor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dlog10.md
  sidebars.json
  versioned_docs/version-1.2/sql-manual/sql-functions/math-functions/degrees.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/degrees.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/degrees.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dfloor.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dlog10.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/degrees.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dfloor.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dlog10.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1822 [Fix](docs)Sql function months_diff,seconds_diff,timediff
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/months-diff.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/seconds-diff.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/timediff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/months-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/seconds-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/timediff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/months-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/seconds-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/timediff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/months-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/seconds-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timediff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/months-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/seconds-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timediff.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/months-diff.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/seconds-diff.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/timediff.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/months-diff.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/seconds-diff.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timediff.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/months-diff.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/seconds-diff.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timediff.md
Labels: approved

#1906 [doc](backup)Modify backup and restore documentation
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/BACKUP.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-BACKUP.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-RESTORE.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-BACKUP.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-RESTORE.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-SNAPSHOT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-SNAPSHOT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-SNAPSHOT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-BACKUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-RESTORE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-SNAPSHOT.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/BACKUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-BACKUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-RESTORE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-BACKUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-RESTORE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-SNAPSHOT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/BACKUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-BACKUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CANCEL-RESTORE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-BACKUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-RESTORE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-SNAPSHOT.md
Labels: approved

#1924 update for regexp serial function.
  docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace-one.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace-one.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-replace-one.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-replace-one.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace-one.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace-one.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp.md
  versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract.md
  versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-replace-one.md
  versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-replace.md
  versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-replace-one.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-replace.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace-one.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace-one.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-replace.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp.md
Labels: approved

#1946 [doc] update recycle statement
  docs/sql-manual/sql-statements/recycle/DROP-CATALOG-RECYCLE-BIN.md
  docs/sql-manual/sql-statements/recycle/RECOVER.md
  docs/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/recycle/DROP-CATALOG-RECYCLE-BIN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/recycle/RECOVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md
Labels: approved

#1996 [Doc] Fix `minute-ceil` function zh document url error
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
Labels: approved

#1997 change file for clean profile
  docs/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/query/CLEAN-ALL-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/session/query/CLEAN-ALL-PROFILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
Labels: approved

#2002 [fix] Fix mixed content of json parse and json search in version 2.1.
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
Labels: approved

#1850 add Bucket
  docs/table-design/data-partitioning/auto-bucket.md
  docs/table-design/data-partitioning/basic-concepts.mdx
  docs/table-design/data-partitioning/data-bucketing.md
  docs/table-design/data-partitioning/dynamic-partitioning.md
  docs/table-design/data-partitioning/manual-bucketing.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/auto-bucket.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/basic-concepts.mdx
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/data-bucketing.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/dynamic-partitioning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/manual-bucketing.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/auto-bucket.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/basic-concepts.mdx
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/data-bucketing.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/dynamic-partitioning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/manual-bucketing.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/auto-bucket.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/basic-concepts.mdx
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/data-bucketing.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/dynamic-partitioning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/manual-bucketing.md
  sidebars.json
  static/images/table-desigin/hash-bucket.png
  static/images/table-desigin/random-bucket.png
  versioned_docs/version-2.1/table-design/data-partitioning/basic-concepts.mdx
  versioned_docs/version-2.1/table-design/data-partitioning/data-bucketing.md
  versioned_docs/version-2.1/table-design/data-partitioning/dynamic-partitioning.md
  versioned_docs/version-3.0/table-design/data-partitioning/basic-concepts.mdx
  versioned_docs/version-3.0/table-design/data-partitioning/data-bucketing.md
  versioned_docs/version-3.0/table-design/data-partitioning/dynamic-partitioning.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1992 [function] refactor some arithmetic functions
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/bin.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/cbrt.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/ceil.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/conv.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/cos.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/floor.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/bin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/cbrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/conv.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/bin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/cbrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/conv.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/sin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/bin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/cbrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/conv.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/bin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/cbrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/conv.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/cos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/bin.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/cbrt.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/ceil.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/conv.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/cos.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/floor.md
  versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/sin.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/bin.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/cbrt.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/ceil.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/conv.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/cos.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/floor.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/bin.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/cbrt.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/ceil.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/conv.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/cos.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/floor.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
Labels: request review

#2001 [doc](function) improve docs from some math functions
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/cosh.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/dround.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/dsqrt.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/e.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/pow.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/cosh.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/dround.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/dsqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/e.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/pow.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/cosh.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dround.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dsqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/e.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/pow.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/cosh.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dround.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dsqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/e.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/pow.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/cosh.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dround.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dsqrt.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/e.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/pow.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/cosh.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dround.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dsqrt.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/e.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/pow.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1964 [doc]Update statistics related sql manual.
  docs/sql-manual/sql-statements/statistics/ANALYZE.md
  docs/sql-manual/sql-statements/statistics/SHOW-ANALYZE.md
  docs/sql-manual/sql-statements/statistics/SHOW-STATS.md
  docs/sql-manual/sql-statements/statistics/SHOW-TABLE-STATS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/statistics/ANALYZE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/statistics/SHOW-ANALYZE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/statistics/SHOW-STATS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/statistics/SHOW-TABLE-STATS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/statistics/ANALYZE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/statistics/SHOW-ANALYZE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/statistics/SHOW-STATS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/statistics/SHOW-TABLE-STATS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/statistics/ANALYZE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/statistics/SHOW-ANALYZE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/statistics/SHOW-STATS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/statistics/SHOW-TABLE-STATS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/statistics/ANALYZE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/statistics/SHOW-ANALYZE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/statistics/SHOW-STATS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/statistics/SHOW-TABLE-STATS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/statistics/ANALYZE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/statistics/SHOW-ANALYZE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/statistics/SHOW-STATS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/statistics/SHOW-TABLE-STATS.md
Labels: request review

#1977 [doc] Update broker instance doc
  docs/sql-manual/sql-statements/cluster-management/instance-management/ADD-BROKER.md
  docs/sql-manual/sql-statements/cluster-management/instance-management/DROP-BROKER.md
  docs/sql-manual/sql-statements/cluster-management/instance-management/SHOW-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/ADD-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/DROP-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/SHOW-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/ADD-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/DROP-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/SHOW-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/ADD-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/DROP-BROKER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/SHOW-BROKER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/ADD-BROKER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/DROP-BROKER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/SHOW-BROKER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/ADD-BROKER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/DROP-BROKER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/SHOW-BROKER.md
Labels: approved

#1902 [docs]Fix statement docs of CANCAL, REFRESH, PAUSE and RESUME MATERIALIZED VIEW
  docs/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
  docs/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW-JOB.md
  docs/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
  docs/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW-JOB.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW-JOB.md
Labels: has comments

#1794 [doc](mtmv) Add more doc for mtmv
  docs/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  docs/query-acceleration/materialized-view/async-materialized-view/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/overview.md
  versioned_docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  versioned_docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/overview.md
  versioned_docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/functions-and-demands.md
  versioned_docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/overview.md
Labels: request review, Need update EN version, Need update version-2.1, Need update version-3.0

#2026 [blog] Update blog
  blog/ai-unicorn-minimax-from-loki-and-built-a-pb-scale-logging-system-with-doris.md
  blog/real-time-data-warehouse-in-TikTok-based-on-doris.md
  src/constant/newsletter.data.ts
Labels: approved

#2027 [docs](ecosystem) Delete hive hll udf of 2.x and 1.2
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/hive-hll-udf.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/hive-hll-udf.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/hive-hll-udf.md
  versioned_docs/version-1.2/ecosystem/hive-hll-udf.md
  versioned_docs/version-2.0/ecosystem/hive-hll-udf.md
  versioned_docs/version-2.1/ecosystem/hive-hll-udf.md
  versioned_sidebars/version-1.2-sidebars.json
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
Labels: approved

#1991 [Doc]positive round round_bankers sign sin
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/positive.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/round-bankers.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/sign.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/positive.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/round-bankers.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/sign.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/positive.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/round-bankers.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sign.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/positive.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/round-bankers.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sign.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sin.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/positive.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/round-bankers.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sign.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/positive.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/round-bankers.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/round.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sign.md
Labels: request review

#1932 [doc] translate explode json array double
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-functions/posexplode.md
Labels: approved

#2031 [docs](sql-statement) Update ALTER SQL_BLOCK_RULE
  docs/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
Labels: request review

#2036 [docs](sql-statement) Update CREATE INDEX
  docs/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
Labels: request review

#2034 [docs](sql-statement) Update CREATE FUNCTION
  docs/sql-manual/sql-statements/function/CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/CREATE-FUNCTION.md
  versioned_docs/version-2.1/sql-manual/sql-statements/function/CREATE-FUNCTION.md
  versioned_docs/version-3.0/sql-manual/sql-statements/function/CREATE-FUNCTION.md
Labels: request review

#2032 [docs](sql-statement) Update create sql block rule
  docs/sql-manual/sql-statements/data-governance/CREATE-SQL_BLOCK_RULE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-governance/CREATE-SQL_BLOCK_RULE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-governance/CREATE-SQL_BLOCK_RULE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-governance/CREATE-SQL_BLOCK_RULE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-governance/CREATE-SQL_BLOCK_RULE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-governance/ALTER-SQL_BLOCK_RULE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-governance/CREATE-SQL_BLOCK_RULE.md
Labels: request review

#2045 [users] Update user logo
  blog/Log-Analysis-How-to-Digest-15-Billion-Logs-Per-Day-and-Keep-Big-Queries-Within-1-Second.md
  src/constant/users.data.json
  static/images/telegram.jpeg
Labels: approved

#2065 update deadlink for en-dev
  docs/admin-manual/auth/authentication-and-authorization.md
  docs/admin-manual/auth/authentication/internal.md
  docs/admin-manual/auth/ldap.md
  docs/admin-manual/auth/user-privilege.md
  docs/data-operate/delete/delete-manual.md
  docs/install/deploy-on-kubernetes/compute-storage-coupled/cluster-operation.md
  docs/install/deploy-on-kubernetes/compute-storage-coupled/install-config-cluster.md
  docs/install/deploy-on-kubernetes/compute-storage-decoupled/install-doris-cluster.md
  docs/install/deploy-on-kubernetes/compute-storage-decoupled/install-fdb.md
  docs/query-data/mysql-compatibility.md
  docs/releasenotes/v2.1/release-2.1.4.md
  docs/sql-manual/sql-data-types/data-type-overview.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-type.md
  docs/sql-manual/sql-functions/table-valued-functions/mv_infos.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/SHOW-COMPUTE-GROUPS.md
  docs/sql-manual/sql-statements/cluster-management/storage-management/SHOW-CACHE-HOTSPOT.md
  docs/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-VAULTS.md
  docs/sql-manual/sql-statements/cluster-management/storage-management/SHOW-WARM-UP-JOB.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/CREATE-ROUTINE-LOAD.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  docs/sql-manual/sql-statements/data-modification/load-and-export/SHOW-STREAM-LOAD.md
  docs/sql-manual/sql-statements/system-info-and-help/SHOW-PROC.md
  docs/sql-manual/sql-statements/table-and-view/async-materialized-view/ALTER-ASYNC-MATERIALIZED-VIEW.md
  docs/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-PARTITION.md
  docs/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-REPLACE.md
  docs/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-ROLLUP.md
  docs/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  docs/table-design/auto-increment.md
  docs/table-design/data-partitioning/common-issues.md
  docs/table-design/overview.md
  docs/table-design/tiered-storage/remote-storage.md
  yarn.lock
Labels: approved

#2066 [improve](data-connect)Add Version Descriptions for Arrow Flight Support in Flink/Spark Doris Connectors
  docs/db-connect/arrow-flight-sql-connect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md
  versioned_docs/version-2.1/db-connect/arrow-flight-sql-connect.md
  versioned_docs/version-3.0/db-connect/arrow-flight-sql-connect.md
Labels: approved

#2011 Installation - update java heap for be configuration
  docs/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  versioned_docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  versioned_docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md
Labels: approved

#2079 [update] Update recent events
  docs/ecosystem/bi/powerbi.md
  docusaurus.config.js
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/bi/powerbi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/bi/powerbi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/bi/powerbi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/bi/powerbi.md
  versioned_docs/version-2.0/ecosystem/bi/powerbi.md
  versioned_docs/version-2.1/ecosystem/bi/powerbi.md
  versioned_docs/version-3.0/ecosystem/bi/powerbi.md
Labels: approved

#2085 [update] Fix download and ecosystem deadlink
  src/constant/download.data.ts
  src/pages/download/index.tsx
  src/pages/ecosystem/cluster-management/index.tsx
Labels: approved

#1714 improve spark connector docs
  docs/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/spark-doris-connector.md
  versioned_docs/version-2.1/ecosystem/spark-doris-connector.md
  versioned_docs/version-3.0/ecosystem/spark-doris-connector.md
Labels: approved

#1953 [Doc]update trash statement
  docs/sql-manual/sql-statements/table-and-view/data-and-status-management/CLEAN-TRASH.md
  docs/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/data-and-status-management/CLEAN-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-reference/Database-Administration-Statements/ADMIN-CLEAN-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-reference/Show-Statements/SHOW-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/ADMIN-CLEAN-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/CLEAN-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/CLEAN-TRASH.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TRASH.md
  versioned_docs/version-1.2/sql-manual/sql-reference/Database-Administration-Statements/ADMIN-CLEAN-TRASH.md
  versioned_docs/version-1.2/sql-manual/sql-reference/Show-Statements/SHOW-TRASH.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/ADMIN-CLEAN-TRASH.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-TRASH.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/CLEAN-TRASH.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TRASH.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/CLEAN-TRASH.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TRASH.md
Labels: has comments

#2003 Show frontend disk
  docs/sql-manual/sql-statements/cluster-management/instance-management/SHOW-FRONTENDS-DISKS.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITION-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/SHOW-FRONTENDS-DISKS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITION-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-reference/Show-Statements/SHOW-ALTER-TABLE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-reference/Show-Statements/SHOW-PARTITION-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-ALTER-TABLE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-FRONTENDS-DISKS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-PARTITION-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/SHOW-FRONTENDS-DISKS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITION-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/SHOW-FRONTENDS-DISKS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITION-ID.md
  versioned_docs/version-1.2/sql-manual/sql-reference/Show-Statements/SHOW-ALTER-TABLE-MATERIALIZED-VIEW.md
  versioned_docs/version-1.2/sql-manual/sql-reference/Show-Statements/SHOW-PARTITION-ID.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-ALTER-TABLE-MATERIALIZED-VIEW.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-FRONTENDS-DISKS.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-PARTITION-ID.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/SHOW-FRONTENDS-DISKS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITION-ID.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/SHOW-FRONTENDS-DISKS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-PARTITION-ID.md
Labels: request review

#2012 fix other functions
  docs/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  docs/sql-manual/sql-functions/aggregate-functions/grouping.md
  docs/sql-manual/sql-functions/scalar-functions/other-functions/convert-to.md
  docs/sql-manual/sql-functions/scalar-functions/other-functions/esquery.md
  docs/sql-manual/sql-functions/scalar-functions/other-functions/field.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/grouping.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/other-functions/convert-to.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/other-functions/esquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/other-functions/field.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/aggregate-functions/grouping.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/convert-to.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/esquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/field.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/grouping.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/other-functions/convert-to.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/other-functions/esquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/other-functions/field.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/grouping.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/other-functions/convert-to.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/other-functions/esquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/other-functions/field.md
  versioned_docs/version-2.0/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  versioned_docs/version-2.0/sql-manual/sql-functions/aggregate-functions/grouping.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/convert-to.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/esquery.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/field.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/grouping.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/other-functions/convert-to.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/other-functions/esquery.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/other-functions/field.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/grouping-id.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/grouping.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/other-functions/convert-to.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/other-functions/esquery.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/other-functions/field.md
Labels: request review

#2077 [improve](stoarge-policy)Add a storage policy statement with a usage description.
  docs/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/storage-management/SHOW STORAGE POLICY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
Labels: approved

#2057 【DOC】update be-http docs
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/be-vlog.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/check-rpc-channel.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/check-tablet-segment.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/checksum.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/compaction-run.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/compaction-status.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/download.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/health.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/meta.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/metrics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/pad-rowset.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/reset-rpc-channel.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/snapshot.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-distribution.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-info.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-migration.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-reload.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-restore.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/version-info.md
Labels: approved

#2131 [update] Update announcementbar
  docusaurus.config.js
Labels: approved

#2115 [doc][feature] add doc about rolling restart after start configuration updated
  docs/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-on-kubernetes/install-config-cluster.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
  versioned_docs/version-2.1/install/deploy-on-kubernetes/install-config-cluster.md
  versioned_docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
Labels: approved

#2144 [download] Update Doris 3.0.4
  docs/releasenotes/all-release.md
  docs/releasenotes/v3.0/release-3.0.4.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v3.0/release-3.0.4.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/releasenotes/v3.0/release-3.0.4.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/v3.0/release-3.0.4.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v3.0/release-3.0.4.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v3.0/release-3.0.4.md
  sidebars.json
  src/constant/download.data.ts
  versioned_docs/version-1.2/releasenotes/all-release.md
  versioned_docs/version-1.2/releasenotes/v3.0/release-3.0.4.md
  versioned_docs/version-2.0/releasenotes/all-release.md
  versioned_docs/version-2.0/releasenotes/v3.0/release-3.0.4.md
  versioned_docs/version-2.1/releasenotes/all-release.md
  versioned_docs/version-2.1/releasenotes/v3.0/release-3.0.4.md
  versioned_docs/version-3.0/releasenotes/all-release.md
  versioned_docs/version-3.0/releasenotes/v3.0/release-3.0.4.md
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved
