Repository apache/doris-website, pull requests merged in 2025-04, with the labels that each got.

#2250 [events] Fix events status
  src/pages/events/index.tsx
Labels: approved

#2253 [events] Update events info
  docusaurus.config.js
Labels: approved

#2264 [fix] Fix typo of admin manual
  docs/admin-manual/log-management/fe-log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/log-management/fe-log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/log-management/fe-log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/log-management/fe-log.md
  versioned_docs/version-2.1/admin-manual/log-management/fe-log.md
  versioned_docs/version-3.0/admin-manual/log-management/fe-log.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/s3.md
Labels: approved

#2252 Fix the soft link error in the document
  docs/install/deploy-manually/integrated-storage-compute-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/integrated-storage-compute-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-manually/integrated-storage-compute-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/integrated-storage-compute-deploy-manually.md
  versioned_docs/version-2.1/install/deploy-manually/integrated-storage-compute-deploy-manually.md
  versioned_docs/version-3.0/install/deploy-manually/integrated-storage-compute-deploy-manually.md
Labels: approved

#2291 [fix] Fix typo that reported by issues
  docs/sql-manual/basic-element/sql-data-types/semi-structured/STRUCT.md
  docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
  docs/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-ADD-GENERATED-COLUMN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/arrays-overlap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-ADD-GENERATED-COLUMN.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-y.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-y.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/arrays-overlap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/arrays-overlap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-ADD-GENERATED-COLUMN.md
  sidebars.json
  versioned_docs/version-1.2/lakehouse/filecache.md
  versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-y.md
  versioned_docs/version-2.0/lakehouse/filecache.md
  versioned_docs/version-2.0/sql-manual/sql-data-types/semi-structured/STRUCT.md
  versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-y.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-JOB.md
  versioned_docs/version-2.1/lakehouse/filecache.md
  versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/STRUCT.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
  versioned_docs/version-3.0/lakehouse/filecache.md
  versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/STRUCT.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/ALTER-TABLE-ADD-GENERATED-COLUMN.md
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#2010 [doc](function) update doc about hll_union/hll_raw_agg
  docs/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
Labels: request review

#1939 [typo](docs) As per doris#37949, starting with versions 2.0.14, 2.1.5 and 3.0.1, support_phrase defaults to true if parser is specified, false otherwise.
  docs/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/inverted-index.md
  versioned_docs/version-2.0/table-design/index/inverted-index.md
  versioned_docs/version-2.1/table-design/index/inverted-index.md
  versioned_docs/version-3.0/table-design/index/inverted-index.md
Labels: approved

#1958 Update bloomfilter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/bloomfilter.md
Labels: approved

#2071 [docs] Support Dictionary
  docs/query-acceleration/dictionary.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/dictionary.md
  sidebars.json
Labels: approved

#2082 Update overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/overview.md
Labels: approved

#2097 Update bitmap.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/bitmap.md
Labels: approved

#2090 Update aggregate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/aggregate.md
Labels: approved

#1959 Update ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
Labels: approved

#2317 [doc] posexplode func
  docs/sql-manual/sql-functions/table-functions/posexplode.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/posexplode-outer.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/posexplode.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-functions/posexplode.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-functions/posexplode-outer.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-functions/posexplode.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-functions/posexplode.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-functions/posexplode.md
Labels: approved

#2188 [Fix](docs)SHOW TABLET, SHOW TABLETS BELONG
  docs/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLET.md
  docs/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLETS-BELONG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLETS-BELONG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-TABLET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-TABLETS-BELONG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLETS-BELONG.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLETS-BELONG.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-TABLET.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-TABLETS-BELONG.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLET.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLETS-BELONG.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLET.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-TABLETS-BELONG.md
Labels: approved

#2220 Update aggregate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/aggregate.md
Labels: approved

#2194 [auth]Ranger default policy description
  docs/admin-manual/auth/authorization/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authorization/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/authorization/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/authorization/ranger.md
  static/images/ranger/default-policy.png
  versioned_docs/version-2.1/admin-manual/auth/authorization/ranger.md
  versioned_docs/version-3.0/admin-manual/auth/authorization/ranger.md
Labels: approved

#2200 [Doc](stmt) Update add follower,add observer, drop follower and drop …
  docs/sql-manual/sql-statements/cluster-management/instance-management/ADD-FOLLOWER.md
  docs/sql-manual/sql-statements/cluster-management/instance-management/ADD-OBSERVER.md
  docs/sql-manual/sql-statements/cluster-management/instance-management/DROP-FOLLOWER.md
  docs/sql-manual/sql-statements/cluster-management/instance-management/DROP-OBSERVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/ADD-FOLLOWER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/ADD-OBSERVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/DROP-FOLLOWER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/instance-management/DROP-OBSERVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/ADD-FOLLOWER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/ADD-OBSERVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/DROP-FOLLOWER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/DROP-OBSERVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/ADD-FOLLOWER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/ADD-OBSERVER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/DROP-FOLLOWER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/DROP-OBSERVER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/ADD-FOLLOWER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/ADD-OBSERVER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/DROP-FOLLOWER.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/instance-management/DROP-OBSERVER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/ADD-FOLLOWER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/ADD-OBSERVER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/DROP-FOLLOWER.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/instance-management/DROP-OBSERVER.md
Labels: request review

#2205 [auth]Add explanation for show grants
  docs/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  docs/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-ROLES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-ROLES.md
Labels: approved

#2168 [function] Fix incomplete window-function introduce
  docs/sql-manual/sql-functions/window-functions/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/window-functions/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/query-data/window-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/window-functions/WINDOW-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/window-functions/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/window-functions/overview.md
  sidebars.json
  versioned_docs/version-2.0/query/query-data/window-function.md
  versioned_docs/version-2.0/sql-manual/sql-functions/window-functions/WINDOW-FUNCTION.md
  versioned_docs/version-2.1/sql-manual/sql-functions/window-functions/overview.md
  versioned_docs/version-3.0/sql-manual/sql-functions/window-functions/overview.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#2177 [doc]Update some incorrect descriptions about fe-config
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md
Labels: approved

#2189 [Fix](doc) timestamp, years-diff,years-sub,to-iso8601,week-ceil,week-floor
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/timestamp.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/to-iso8601.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/week-ceil.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/week-floor.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/years-add.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/years-diff.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/years-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/timestamp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/to-iso8601.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/week-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/week-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/years-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/years-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/years-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/years-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/years-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/years-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timestamp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/to-iso8601.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/week-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/week-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/years-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/years-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/years-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timestamp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/to-iso8601.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/week-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/week-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/years-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/years-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/years-sub.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/years-add.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/years-diff.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/years-sub.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timestamp.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/to-iso8601.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/week-ceil.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/week-floor.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/years-add.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/years-diff.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/years-sub.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/timestamp.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timestamp.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/to-iso8601.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/week-ceil.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/week-floor.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/years-add.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/years-diff.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/years-sub.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/timestamp.md
Labels: request review

#2297 [fix]The Chinese document for drop SQL block rule is displayed in English
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-governance/DROP-SQL_BLOCK_RULE.md
Labels: approved

#2219 Update overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/overview.md
Labels: approved

#2156 [mtmv]show create materialized view
  docs/query-acceleration/materialized-view/async-materialized-view/faq.md
  docs/sql-manual/sql-statements/table-and-view/async-materialized-view/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
  docs/sql-manual/sql-statements/table-and-view/sync-materialized-view/SHOW-CREATE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/async-materialized-view/faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/async-materialized-view/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/sync-materialized-view/SHOW-CREATE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/async-materialized-view/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/sync-materialized-view/SHOW-CREATE-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/async-materialized-view/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/sync-materialized-view/SHOW-CREATE-MATERIALIZED-VIEW.md
  sidebars.json
  versioned_docs/version-2.1/query-acceleration/materialized-view/async-materialized-view/faq.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/async-materialized-view/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/sync-materialized-view/SHOW-CREATE-MATERIALIZED-VIEW.md
  versioned_docs/version-3.0/query-acceleration/materialized-view/async-materialized-view/faq.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/async-materialized-view/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/sync-materialized-view/SHOW-CREATE-MATERIALIZED-VIEW.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review

#2305 [opt] memory debug tools
  community/developer-guide/debug-tool.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/debug-tool.md
Labels: request review

#2320 [Feat]:add forum entry to toc
  src/components/Icons/forum-icon.tsx
  src/components/Icons/github-icon.tsx
  src/components/Icons/home-icon.tsx
  src/components/Icons/pdf-icon.tsx
  src/components/Icons/slack-icon.tsx
  src/scss/components/toc.scss
  src/theme/TOC/index.tsx
Labels: request review

#2206 [Fix]Add necessary parameters for using n-gram bloomfilter index
  docs/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
  versioned_docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
Labels: approved

#2316 [feat](maxcompute)add from maxcompute to doris best-practices.
  docs/lakehouse/best-practices/doris-maxcompute.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/best-practices/doris-maxcompute.md
  sidebars.json
Labels: request review, has comments, Need update EN version

#2281 [feat](openx-json) add openx json doc
  docs/lakehouse/file-formats/text.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/file-formats/text.md
Labels: approved

#2318 [doc](load) add bigquery datasource doc
  docs/data-operate/import/data-source/bigquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/bigquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/bigquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/bigquery.md
  sidebars.json
  static/images/data-operate/gcs_export.png
  versioned_docs/version-2.1/data-operate/import/data-source/bigquery.md
  versioned_docs/version-3.0/data-operate/import/data-source/bigquery.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review

#2236 [feat](docs) Add aws_authentication_and_authorization.md
  docs/admin-manual/auth/integrations/aws-authentication-and-authorization.md
  docs/data-operate/import/data-source/amazon-s3.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  docs/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/integrations/aws-authentication-and-authorization.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/amazon-s3.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/s3.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/integrations/aws-authentication-and-authorization.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/amazon-s3.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  sidebars.json
  static/images/integrations/assumed_role_flow.png
  static/images/integrations/create_iam_user.png
  static/images/integrations/ec2_instance.png
  static/images/integrations/iam_user_attach_policy1.png
  static/images/integrations/iam_user_attach_policy2.png
  static/images/integrations/iam_user_create_ak_sk.png
  static/images/integrations/source_role_permission.png
  static/images/integrations/target_role_permission1.png
  static/images/integrations/target_role_permission2.png
  static/images/integrations/target_role_trust_policy.png
  versioned_docs/version-3.0/admin-manual/auth/integrations/aws-authentication-and-authorization.md
  versioned_docs/version-3.0/data-operate/import/data-source/amazon-s3.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review, has comments

#2322 [doc]update description in log function
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/log.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/log.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/log.md
Labels: approved

#2329 [opt](group commit) remove group_commit_memory_rows_for_max_filter_ra…
  docs/admin-manual/config/be-config.md
  docs/data-operate/import/group-commit-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/group-commit-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/group-commit-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/group-commit-manual.md
  versioned_docs/version-2.1/admin-manual/config/be-config.md
  versioned_docs/version-2.1/data-operate/import/group-commit-manual.md
  versioned_docs/version-3.0/admin-manual/config/be-config.md
  versioned_docs/version-3.0/data-operate/import/group-commit-manual.md
Labels: approved

#2330 [fix] Fix deadlink and typo issues
  blog/why-apache-doris-is-best-alternatives-for-real-time-analytics.md
  docs/query-data/udf/java-user-defined-function.md
  docs/sql-manual/basic-element/sql-data-types/data-type-overview.md
  docs/table-design/data-type.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/udf/java-user-defined-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/data-type-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-type.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/udf/java-user-defined-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/data-type-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-type.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/data-type-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-type.md
  versioned_docs/version-2.1/query-data/udf/java-user-defined-function.md
  versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/data-type-overview.md
  versioned_docs/version-2.1/table-design/data-type.md
  versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/data-type-overview.md
  versioned_docs/version-3.0/table-design/data-type.md
Labels: approved

#2328 Change Quick Start Shell
  docs/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/quick-start.md
  static/files/start-doris.sh
  versioned_docs/version-2.1/gettingStarted/quick-start.md
  versioned_docs/version-3.0/gettingStarted/quick-start.md
Labels: approved

#2325 [improve](datasource) update typo for datasource
  docs/data-operate/import/data-source/bigquery.md
  docs/data-operate/import/data-source/snowflake.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/bigquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/snowflake.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/bigquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/snowflake.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/bigquery.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/snowflake.md
  versioned_docs/version-2.1/data-operate/import/data-source/bigquery.md
  versioned_docs/version-2.1/data-operate/import/data-source/snowflake.md
  versioned_docs/version-3.0/data-operate/import/data-source/bigquery.md
  versioned_docs/version-3.0/data-operate/import/data-source/snowflake.md
Labels: approved

#2333 [opt](load) add load faq
  docs/faq/load-faq.md
  docs/faq/routineload-faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/faq/load-faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/faq/load-faq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/faq/load-faq.md
  sidebars.json
  versioned_docs/version-2.1/faq/load-faq.md
  versioned_docs/version-2.1/faq/routineload-faq.md
  versioned_docs/version-3.0/faq/load-faq.md
  versioned_docs/version-3.0/faq/routineload-faq.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: has comments

#2344 [update] Update 3.0.5 release
  blog/release-note-3.0.5.md
  docs/releasenotes/all-release.md
  docs/releasenotes/v3.0/release-3.0.5.md
  i18n/en/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/routine_load_job.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v3.0/release-3.0.5.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/v3.0/release-3.0.5.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v3.0/release-3.0.5.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v3.0/release-3.0.5.md
  sidebars.json
  src/constant/download.data.ts
  src/constant/newsletter.data.ts
  static/images/3.0.5.jpeg
  versioned_docs/version-2.0/releasenotes/all-release.md
  versioned_docs/version-2.0/releasenotes/v3.0/release-3.0.5.md
  versioned_docs/version-2.1/releasenotes/all-release.md
  versioned_docs/version-2.1/releasenotes/v3.0/release-3.0.5.md
  versioned_docs/version-3.0/releasenotes/all-release.md
  versioned_docs/version-3.0/releasenotes/v3.0/release-3.0.5.md
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved
