Repository apache/doris-website, pull requests merged in 2025-05, with the labels that each got.

#2342 add new notice of json load
  docs/data-operate/import/file-format/json.md
  docs/data-operate/import/import-way/broker-load-manual.md
  docs/data-operate/import/import-way/routine-load-manual.md
  docs/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/file-format/json.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/file-format/json.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/file-format/json.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
  versioned_docs/version-2.1/data-operate/import/file-format/json.md
  versioned_docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
  versioned_docs/version-3.0/data-operate/import/file-format/json.md
  versioned_docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
  versioned_docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
Labels: approved

#2183 [Fix](DML) Add quick conclusion for insert overwrite behaviour and fix wrong version label in English docs
  docs/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
Labels: approved

#2352 [Fix](dictionary) Fix wrong description in dictionary docs
  docs/query-acceleration/dictionary.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/dictionary.md
Labels: approved

#2197 fix the document of TO_DATE, TO_DAYS, year_floor, WEEKS_ADD, WEEKS_DIFF, WEEKS_SUB function
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/to-date.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/to-days.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-add.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-diff.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-sub.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/year-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/to-date.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/to-days.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/year-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/to-date.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/to-days.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/year-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/to-date.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/to-days.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-diff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/year-floor.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/to-date.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/to-days.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-add.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-diff.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-sub.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/year-floor.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/to-date.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/to-days.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-add.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-diff.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/weeks-sub.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/year-floor.md
Labels: has comments

#2334 [opt](memory) Opt memory heap profile
  community/developer-guide/debug-tool.md
  docs/admin-manual/trouble-shooting/memory-management/memory-analysis/heap-profile-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/debug-tool.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/trouble-shooting/memory-management/memory-analysis/heap-profile-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/trouble-shooting/memory-management/memory-analysis/heap-profile-memory-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/trouble-shooting/memory-management/memory-analysis/heap-profile-memory-analysis.md
  versioned_docs/version-2.1/admin-manual/trouble-shooting/memory-management/memory-analysis/heap-profile-memory-analysis.md
  versioned_docs/version-3.0/admin-manual/trouble-shooting/memory-management/memory-analysis/heap-profile-memory-analysis.md
Labels: request review

#2357 fxi return type of REGEXP_EXTRACT_ALL
  docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
Labels: approved

#2343 [doc](bi)update the way to connect doris by tableau
  docs/ecosystem/bi/tableau.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/bi/tableau.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/bi/tableau.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/bi/tableau.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/bi/tableau.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/bi/tableau.md
  versioned_docs/version-1.2/ecosystem/bi/tableau.md
  versioned_docs/version-2.0/ecosystem/bi/tableau.md
  versioned_docs/version-2.1/ecosystem/bi/tableau.md
  versioned_docs/version-3.0/ecosystem/bi/tableau.md
Labels: approved

#2145 fix : fix format of flink
  docs/data-operate/import/data-source/flink.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/flink.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/flink.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/flink.md
  versioned_docs/version-2.1/data-operate/import/data-source/flink.md
  versioned_docs/version-3.0/data-operate/import/data-source/flink.md
Labels: approved

#2386 Update Cisco blog
  blog/doris-supercharges-cisco-webex-data-platform.md
  blog/release-note-2.1.9.md
  blog/tencent-music-migrate-elasticsearch-to-doris.md
  docs/observability/overview.mdx
  i18n/zh-CN/docusaurus-plugin-content-docs/current/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/observability/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/observability/log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v2.1/release-2.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/releasenotes/v2.1/release-2.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/v2.1/release-2.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/observability/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/observability/log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v2.1/release-2.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/observability/log-storage-analysis.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/observability/log.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v2.1/release-2.1.0.md
  src/components/recent-blogs/recent-blogs.data.ts
  src/constant/newsletter.data.ts
  static/images/blogs/cisco-webex/Less-failures-and-higher-reliability-new-solutions.png
  static/images/blogs/cisco-webex/doris-supercharges-cisco-webex-data-platform.jpg
  static/images/blogs/cisco-webex/less-failures-and-higher-reliability.png
  static/images/blogs/cisco-webex/platform-1.0-replace-Trino-Kyuubi-Pinot-Iceberg.png
  static/images/blogs/cisco-webex/platform-2.0-Apache-Doris.png
  static/images/blogs/cisco-webex/unified-access-control-new-solution.png
  static/images/blogs/cisco-webex/unified-access-control-old-solution.png
  static/images/blogs/cisco-webex/unity-drives-efficiency-new-solution.png
  static/images/blogs/cisco-webex/unity-drives-efficiency-old-solution.png
  static/images/doris-supercharges-cisco-webex-data-platform.jpg
  static/images/observability/studio-discover.jpeg
  versioned_docs/version-2.1/observability/overview.mdx
  versioned_docs/version-2.1/practical-guide/log-storage-analysis.md
  versioned_docs/version-3.0/observability/overview.mdx
Labels: approved

#2387 Update slack link
  community/how-to-contribute/contribute-to-doris.md
  community/join-community.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute/contribute-to-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/join-community.md
  src/pages/index.tsx
  src/theme/Footer/index.tsx
  src/theme/Navbar/Content/components/NavbarCommon.tsx
  src/theme/TOC/index.tsx
Labels: approved

#2391 Update Blog
  blog/doris-supercharges-cisco-webex-data-platform.md
  blog/release-note-3.0.5.md
  docs/gettingStarted/what-is-apache-doris.md
  src/constant/newsletter.data.ts
  src/constant/users.data.json
  static/images/blogs/cisco-webex/Less-failures-and-higher-reliability-new-solutions.png
  static/images/blogs/cisco-webex/doris-supercharges-cisco-webex-data-platform.jpg
  static/images/blogs/cisco-webex/less-failures-and-higher-reliability.png
  static/images/blogs/cisco-webex/platform-1.0-replace-Trino-Kyuubi-Pinot-Iceberg.png
  static/images/blogs/cisco-webex/platform-2.0-Apache-Doris.png
  static/images/blogs/cisco-webex/unified-access-control-new-solution.png
  static/images/blogs/cisco-webex/unified-access-control-old-solution.png
  static/images/blogs/cisco-webex/unity-drives-efficiency-new-solution.png
  static/images/blogs/cisco-webex/unity-drives-efficiency-old-solution.png
  versioned_docs/version-1.2/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-2.0/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-2.1/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-3.0/gettingStarted/what-is-apache-doris.md
Labels: approved

#2395 Update 2.1.10 release
  blog/release-note-2.1.10.md
  blog/release-note-3.0.5.md
  docs/releasenotes/all-release.md
  docs/releasenotes/v2.1/release-2.1.10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v2.1/release-2.1.10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/v2.1/release-2.1.10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v2.1/release-2.1.10.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v2.1/release-2.1.10.md
  sidebars.json
  src/constant/download.data.ts
  src/constant/newsletter.data.ts
  static/images/2.1.10.jpg
  versioned_docs/version-2.0/releasenotes/all-release.md
  versioned_docs/version-2.0/releasenotes/v2.1/release-2.1.10.md
  versioned_docs/version-2.1/releasenotes/all-release.md
  versioned_docs/version-2.1/releasenotes/v2.1/release-2.1.10.md
  versioned_docs/version-3.0/releasenotes/all-release.md
  versioned_docs/version-3.0/releasenotes/v2.1/release-2.1.10.md
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#2300 Remove the description that the parameter does not support variables
  docs/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
Labels: dependencies

#2410 [fix] Fix picture of blog
  blog/apache-doris-speeds-up-data-reporting-tagging-and-data-lake-analytics.md
  static/images/blogs/speed-up-lakehouse/average-query-response-time.png
  static/images/blogs/speed-up-lakehouse/data-synchronization-size-and-duration.png
  static/images/blogs/speed-up-lakehouse/from-clickHouse-mysql-to-apache-doris.png
  static/images/blogs/speed-up-lakehouse/query-response-time-percentile.png
  static/images/blogs/speed-up-lakehouse/skein.png
  static/images/blogs/speed-up-lakehouse/tagging-services.png
Labels: approved

#2416 [Enhancement] (GEO) Support MultiPolygon for Geometry functions
  docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
Labels: approved

#2157 [feat] suppor the spatial function docs, like ST_Intersects, ST_Disjo…
  docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
  docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
  docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#2418 Update observability events
  docusaurus.config.js
  src/pages/events/index.tsx
  static/images/events/observability-webinar-250507.jpeg
  static/images/events/observability-webinar-250514.jpg
  static/images/events/observability-webinar-250528.jpeg
Labels: approved
