Repository apache/doris-website, pull requests merged in 2025-01, with the labels that each got.

#1685 fix some problems and add upgrade for ccr
  docs/admin-manual/data-admin/ccr/manual.md
  docs/admin-manual/data-admin/ccr/performance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/performance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr/manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr/performance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/performance.md
  versioned_docs/version-2.1/admin-manual/data-admin/ccr/manual.md
  versioned_docs/version-2.1/admin-manual/data-admin/ccr/performance.md
  versioned_docs/version-3.0/admin-manual/data-admin/ccr/manual.md
  versioned_docs/version-3.0/admin-manual/data-admin/ccr/performance.md
Labels: request review

#1626 fix some param error in fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
  versioned_docs/version-2.0/admin-manual/config/fe-config.md
  versioned_docs/version-2.1/admin-manual/config/fe-config.md
Labels: request review

#1659 update lakehouse best practices
  docs/lakehouse/lakehouse-best-practices/doris-hudi.md
  docs/lakehouse/lakehouse-best-practices/doris-iceberg.md
  docs/lakehouse/lakehouse-best-practices/doris-lakesoul.md
  docs/lakehouse/lakehouse-best-practices/doris-paimon.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/lakehouse-best-practices/doris-hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/lakehouse-best-practices/doris-iceberg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/lakehouse-best-practices/doris-lakesoul.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/lakehouse-best-practices/doris-paimon.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse-best-practices/doris-hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse-best-practices/doris-iceberg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse-best-practices/doris-lakesoul.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse-best-practices/doris-paimon.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/lakehouse-best-practices/doris-hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/lakehouse-best-practices/doris-iceberg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/lakehouse-best-practices/doris-lakesoul.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/lakehouse-best-practices/doris-paimon.md
  sidebars.json
  versioned_docs/version-2.1/lakehouse/lakehouse-best-practices/doris-hudi.md
  versioned_docs/version-2.1/lakehouse/lakehouse-best-practices/doris-iceberg.md
  versioned_docs/version-2.1/lakehouse/lakehouse-best-practices/doris-lakesoul.md
  versioned_docs/version-2.1/lakehouse/lakehouse-best-practices/doris-paimon.md
  versioned_docs/version-3.0/lakehouse/lakehouse-best-practices/doris-hudi.md
  versioned_docs/version-3.0/lakehouse/lakehouse-best-practices/doris-iceberg.md
  versioned_docs/version-3.0/lakehouse/lakehouse-best-practices/doris-lakesoul.md
  versioned_docs/version-3.0/lakehouse/lakehouse-best-practices/doris-paimon.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1661 Installation optimization
  docs/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  docs/install/preparation/cluster-planning.md
  docs/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/cluster-planning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/cluster-planning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/preparation/os-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/cluster-planning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/env-checking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/preparation/os-checking.md
  versioned_docs/version-2.1/install/preparation/cluster-planning.md
  versioned_docs/version-2.1/install/preparation/env-checking.md
  versioned_docs/version-3.0/install/preparation/cluster-planning.md
  versioned_docs/version-3.0/install/preparation/env-checking.md
Labels: approved

#1665 Upgrade doc
  docs/admin-manual/cluster-management/upgrade.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/cluster-management/upgrade.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/cluster-management/upgrade.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/cluster-management/upgrade.md
  versioned_docs/version-2.1/admin-manual/cluster-management/upgrade.md
  versioned_docs/version-3.0/admin-manual/cluster-management/upgrade.md
Labels: approved

#1670 Table design
  docs/table-design/data-model/aggregate.md
  docs/table-design/data-model/duplicate.md
  docs/table-design/data-model/overview.md
  docs/table-design/data-model/unique.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/aggregate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/duplicate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/unique.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/aggregate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/duplicate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/unique.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/aggregate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/duplicate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/unique.md
  static/images/table-desigin/aggrate-key-model-insert.png
  static/images/table-desigin/columnar-storage.png
  static/images/table-desigin/duplicate-table-insert.png
  static/images/table-desigin/state-func-group-concat-state-result-1.png
  static/images/table-desigin/state-func-group-concat-state-result-2.png
  static/images/table-desigin/unique-key-model-insert.png
  versioned_docs/version-2.1/table-design/data-model/aggregate.md
  versioned_docs/version-2.1/table-design/data-model/duplicate.md
  versioned_docs/version-2.1/table-design/data-model/overview.md
  versioned_docs/version-2.1/table-design/data-model/unique.md
  versioned_docs/version-3.0/table-design/data-model/aggregate.md
  versioned_docs/version-3.0/table-design/data-model/duplicate.md
  versioned_docs/version-3.0/table-design/data-model/overview.md
  versioned_docs/version-3.0/table-design/data-model/unique.md
Labels: approved

#1687 [doc](update) Address comment on update overview and re-translate english doc by LLM
  docs/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-overview.md
  versioned_docs/version-2.1/data-operate/update/update-overview.md
  versioned_docs/version-3.0/data-operate/update/update-overview.md
Labels: approved

#1690 update sidebar for security
  i18n/zh-CN/docusaurus-plugin-content-docs/current.json
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authentication-and-authorization.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/authentication-and-authorization.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/authentication-and-authorization.md
  sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1484 [doc] update spark load 24.0.0 version
  docs/ecosystem/spark-load.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/spark-load.md
  sidebars.json
Labels: approved, Need update version-2.1, Need update version-3.0

#1688 auzre is not supported in 2.1
  docs/admin-manual/data-admin/backup-restore/backup.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/backup-restore/backup.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/backup-restore/backup.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/backup-restore/backup.md
  versioned_docs/version-2.1/admin-manual/data-admin/backup-restore/backup.md
  versioned_docs/version-3.0/admin-manual/data-admin/backup-restore/backup.md
Labels: approved

#1673 add hudi_meta tvf
  docs/lakehouse/datalake-analytics/hudi.md
  docs/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  versioned_docs/version-2.1/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  versioned_docs/version-3.0/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
Labels: approved

#1428 [ecosystem]Improve kafka synchronization json best practices
  docs/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-kafka-connector.md
  versioned_docs/version-2.0/ecosystem/doris-kafka-connector.md
  versioned_docs/version-2.1/ecosystem/doris-kafka-connector.md
  versioned_docs/version-3.0/ecosystem/doris-kafka-connector.md
Labels: has comments

#1455 [doc]The maximum character length of the load label
  docs/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md
  versioned_docs/version-2.0/admin-manual/config/fe-config.md
  versioned_docs/version-2.1/admin-manual/config/fe-config.md
  versioned_docs/version-3.0/admin-manual/config/fe-config.md
Labels: approved

#1704 [update] Delete date floor function of 2.0
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/date-floor.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/date-floor.md
  versioned_sidebars/version-2.0-sidebars.json
Labels: approved

#1708 remove hudi_meta docs in 3.0 and 2.1 because not releaseed
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/hudi.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  versioned_docs/version-2.1/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
  versioned_docs/version-3.0/lakehouse/datalake-analytics/hudi.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
Labels: approved

#1692 Update quick-start.md
  docs/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/quick-start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/quick-start.md
  versioned_docs/version-2.1/gettingStarted/quick-start.md
  versioned_docs/version-3.0/gettingStarted/quick-start.md
Labels: approved

#1391 [fix](outfile/export) refactor the documents of `Outfile` and `Export`
  docs/data-operate/export/export-manual.md
  docs/data-operate/export/outfile.md
  docs/sql-manual/sql-statements/Data-Manipulation-Statements/OUTFILE.md
  docs/sql-manual/sql-statements/Show-Statements/SHOW-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/export/export-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/export/outfile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/OUTFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/export/export-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/export/outfile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/export/export-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/export/outfile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  versioned_docs/version-2.1/data-operate/export/export-manual.md
  versioned_docs/version-2.1/data-operate/export/outfile.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
  versioned_docs/version-3.0/data-operate/export/export-manual.md
  versioned_docs/version-3.0/data-operate/export/outfile.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
Labels: Reviewed

#1677 [ranger]Different versions use different configuration files
  docs/admin-manual/auth/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/ranger.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/ranger.md
  static/images/ranger/catalog.png
  static/images/ranger/column.png
  static/images/ranger/database.png
  static/images/ranger/global.png
  static/images/ranger/group1.png
  static/images/ranger/resource.png
  static/images/ranger/table.png
  versioned_docs/version-2.1/admin-manual/auth/ranger.md
  versioned_docs/version-3.0/admin-manual/auth/ranger.md
Labels: bug, Reviewed

#1721 [doc](data update)Address comment on update of agg model and translate en doc by LLM
  docs/data-operate/update/update-of-aggregate-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-aggregate-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-of-aggregate-model.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-of-aggregate-model.md
  versioned_docs/version-2.1/data-operate/update/update-of-aggregate-model.md
  versioned_docs/version-3.0/data-operate/update/update-of-aggregate-model.md
Labels: request review

#1719 Address comment on unique update.md and translate en doc by LLM
  docs/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/unique-update.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/unique-update.md
  versioned_docs/version-2.1/data-operate/update/unique-update.md
  versioned_docs/version-3.0/data-operate/update/unique-update.md
Labels: request review

#1754 Fix incubator for 2.1/3.0/dev/ cn & en
  docs/benchmark/ssb.md
  docs/ecosystem/datax.md
  docs/ecosystem/doris-streamloader.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/datax.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-streamloader.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/datax.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/doris-streamloader.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/join-optimization/bucket-shuffle-join.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/join-optimization/colocation-join.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/join-optimization/runtime-filter.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/udf/remote-user-defined-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/releasenotes/v1.1/release-1.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/datax.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-streamloader.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v1.1/release-1.1.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/be-config.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-streamloader.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/spark-doris-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v1.1/release-1.1.0.md
  versioned_docs/version-2.0/admin-manual/config/be-config.md
  versioned_docs/version-2.0/benchmark/ssb.md
  versioned_docs/version-2.0/ecosystem/datax.md
  versioned_docs/version-2.0/ecosystem/doris-streamloader.md
  versioned_docs/version-2.0/query/join-optimization/bucket-shuffle-join.md
  versioned_docs/version-2.0/query/join-optimization/colocation-join.md
  versioned_docs/version-2.0/query/join-optimization/runtime-filter.md
  versioned_docs/version-2.0/query/udf/remote-user-defined-function.md
  versioned_docs/version-2.1/admin-manual/config/be-config.md
  versioned_docs/version-2.1/benchmark/ssb.md
  versioned_docs/version-2.1/ecosystem/datax.md
  versioned_docs/version-2.1/ecosystem/doris-streamloader.md
  versioned_docs/version-3.0/admin-manual/config/be-config.md
  versioned_docs/version-3.0/benchmark/ssb.md
  versioned_docs/version-3.0/ecosystem/datax.md
  versioned_docs/version-3.0/ecosystem/doris-streamloader.md
Labels: approved

#1753 [chore]:Improve the md-bold-plugin plugin
  config/markdown-bold-plugin.js
  docs/admin-manual/cluster-management/time-zone.md
  docusaurus.config.js
  src/theme/SearchBar/SearchBar.module.css
  versioned_docs/version-2.0/admin-manual/cluster-management/time-zone.md
  versioned_docs/version-2.1/admin-manual/cluster-management/time-zone.md
  versioned_docs/version-3.0/admin-manual/cluster-management/time-zone.md
Labels: approved

#1784 [doc](load) optimize load doc
  docs/data-operate/import/data-source/kafka.md
  docs/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/local-file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
  versioned_docs/version-2.1/data-operate/import/data-source/kafka.md
  versioned_docs/version-2.1/data-operate/import/data-source/local-file.md
  versioned_docs/version-3.0/data-operate/import/data-source/kafka.md
  versioned_docs/version-3.0/data-operate/import/data-source/local-file.md
Labels: request review

#1757 update table-design sidebar
  sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1734 add dynamic-partition
  docs/table-design/data-partitioning/dynamic-partitioning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/dynamic-partitioning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/dynamic-partitioning.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/dynamic-partitioning.md
  static/images/getting-started/dynamic-partition.png
  versioned_docs/version-2.1/table-design/data-partitioning/dynamic-partitioning.md
  versioned_docs/version-3.0/table-design/data-partitioning/dynamic-partitioning.md
Labels: has comments

#1785 [doc](table-temp-partition) address comments and translate en doc by LLM
  docs/data-operate/delete/table-temp-partition.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/table-temp-partition.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/table-temp-partition.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/table-temp-partition.md
  versioned_docs/version-2.1/data-operate/delete/table-temp-partition.md
  versioned_docs/version-3.0/data-operate/delete/table-temp-partition.md
Labels: request review

#1782 [doc](trancate table) address comment and update english doc by LLM
  docs/data-operate/delete/truncate-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/truncate-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/truncate-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/truncate-manual.md
  versioned_docs/version-2.1/data-operate/delete/truncate-manual.md
  versioned_docs/version-3.0/data-operate/delete/truncate-manual.md
Labels: approved

#1781 [doc](Atomicity Replace) address comments and translate en doc by LLM
  docs/data-operate/delete/atomicity-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/atomicity-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/atomicity-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/atomicity-replace.md
  versioned_docs/version-2.1/data-operate/delete/atomicity-replace.md
  versioned_docs/version-3.0/data-operate/delete/atomicity-replace.md
Labels: request review

#1750 [opt](sc) optimize sc documents
  docs/sql-manual/sql-statements/Show-Statements/SHOW-ALTER.md
  docs/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-ALTER.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-ALTER-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/schema-change.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-ALTER-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/schema-change.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-ALTER-TABLE.md
  versioned_docs/version-2.1/table-design/schema-change.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-ALTER-TABLE.md
  versioned_docs/version-3.0/table-design/schema-change.md
Labels: request review

#1787 update java-udf for 2.1 & 3.0
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/udf/java-user-defined-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/udf/java-user-defined-function.md
  versioned_docs/version-2.1/query-data/udf/java-user-defined-function.md
  versioned_docs/version-3.0/query-data/udf/java-user-defined-function.md
Labels: approved

#1824 [doc] Add sql function PERCENTILE SQL Manual
  docs/sql-manual/sql-functions/aggregate-functions/percentile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile.md
Labels: approved

#1834 [update] Delete invalid vable value function docs
  docs/sql-manual/sql-functions/table-valued-functions/group-commit.md
  docs/sql-manual/sql-functions/table-valued-functions/http-stream.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/group-commit.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/http-stream.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/group-commit.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/http-stream.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/group-commit.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/http-stream.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/group-commit.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/http-stream.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/group-commit.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/http-stream.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1867 [doc](update-of-agg-model) fix title error for en doc
  docs/data-operate/update/update-of-aggregate-model.md
  versioned_docs/version-2.1/data-operate/update/update-of-aggregate-model.md
  versioned_docs/version-3.0/data-operate/update/update-of-aggregate-model.md
Labels: approved

#1809 [doc] Fix json_array zh_doc
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
Labels: approved

#1873 [fix] Fix en docs typo
  docs/gettingStarted/what-is-apache-doris.md
  docs/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/what-is-apache-doris.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/what-is-apache-doris.md
  static/images/getting-started/apache-doris-technical-compute-storage-decouple-overview.jpg
  static/images/getting-started/apache-doris-technical-compute-storage-decouple-overview.png
  versioned_docs/version-3.0/gettingStarted/what-is-apache-doris.md
  versioned_docs/version-3.0/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
Labels: approved

#1795 [ecosystem]fix kafka server prompt address
  docs/data-operate/import/data-source/kafka.md
  docs/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-kafka-connector.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/kafka.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-kafka-connector.md
  versioned_docs/version-2.0/ecosystem/doris-kafka-connector.md
  versioned_docs/version-2.1/data-operate/import/data-source/kafka.md
  versioned_docs/version-2.1/ecosystem/doris-kafka-connector.md
  versioned_docs/version-3.0/data-operate/import/data-source/kafka.md
  versioned_docs/version-3.0/ecosystem/doris-kafka-connector.md
Labels: approved

#1872 [opt](function) optimize some map function docs
  docs/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-key.md
  docs/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-value.md
  docs/sql-manual/sql-functions/scalar-functions/map-functions/map-keys.md
  docs/sql-manual/sql-functions/scalar-functions/map-functions/map-size.md
  docs/sql-manual/sql-functions/scalar-functions/map-functions/map-values.md
  docs/sql-manual/sql-functions/scalar-functions/map-functions/map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-key.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-value.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map-keys.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map-size.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map-values.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-key.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-value.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-keys.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-size.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-values.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-key.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-value.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-keys.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-size.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-values.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-key.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-value.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-keys.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-size.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map-values.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-key.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-contains-value.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-keys.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-size.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map-values.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map.md
Labels: approved

#1863 [doc](batch delete) address comment and translate en doc by LLM
  docs/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/batch-delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/batch-delete-manual.md
  versioned_docs/version-2.1/data-operate/delete/batch-delete-manual.md
  versioned_docs/version-3.0/data-operate/delete/batch-delete-manual.md
Labels: approved

#1866 [doc](delete manual) address comments and translate en doc by LLM
  docs/data-operate/delete/delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/delete-manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/delete-manual.md
  versioned_docs/version-2.1/data-operate/delete/delete-manual.md
  versioned_docs/version-3.0/data-operate/delete/delete-manual.md
Labels: bug, approved

#1877 [doc]Fix approx-count-distinct and orthogonal-bitmap-union-count func…
  docs/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
  docs/sql-manual/sql-functions/aggregate-functions/orthogonal-bitmap-union-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/orthogonal-bitmap-union-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/orthogonal-bitmap-union-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/orthogonal-bitmap-union-count.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/orthogonal-bitmap-union-count.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/orthogonal-bitmap-union-count.md
Labels: approved

#1833 [doc]Refresh Character Set Statement Document Modification
  docs/sql-manual/sql-statements/character-set/SHOW-CHARSET.md
  docs/sql-manual/sql-statements/character-set/SHOW-COLLATION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/character-set/SHOW-CHARSET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/character-set/SHOW-COLLATION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/character-set/SHOW-CHARSET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/character-set/SHOW-COLLATION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/character-set/SHOW-CHARSET.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/character-set/SHOW-COLLATION.md
  versioned_docs/version-2.1/sql-manual/sql-statements/character-set/SHOW-CHARSET.md
  versioned_docs/version-2.1/sql-manual/sql-statements/character-set/SHOW-COLLATION.md
  versioned_docs/version-3.0/sql-manual/sql-statements/character-set/SHOW-CHARSET.md
  versioned_docs/version-3.0/sql-manual/sql-statements/character-set/SHOW-COLLATION.md
Labels: approved

#1807 improve the article format of backends() and frontends() function
  docs/sql-manual/sql-functions/table-valued-functions/backends.md
  docs/sql-manual/sql-functions/table-valued-functions/frontends.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/backends.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/frontends.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/backends.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/frontends.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/backends.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/frontends.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/backends.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/frontends.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/backends.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/frontends.md
Labels: approved

#1812 improve catalogs() and frontends_disks() function article format
  docs/sql-manual/sql-functions/table-valued-functions/catalogs.md
  docs/sql-manual/sql-functions/table-valued-functions/frontends_disks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/catalogs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/frontends_disks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/catalogs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/frontends_disks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/catalogs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/frontends_disks.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/catalogs.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/frontends_disks.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/catalogs.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/frontends_disks.md
Labels: approved

#1828 improve the article format of hdfs() and mv_infos() function
  docs/sql-manual/sql-functions/table-valued-functions/hdfs.md
  docs/sql-manual/sql-functions/table-valued-functions/mv_infos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/hdfs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/mv_infos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/hdfs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/mv_infos.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/hdfs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/mv_infos.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/hdfs.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/mv_infos.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/hdfs.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/mv_infos.md
Labels: approved

#1844 improve query(), number(),tasks(),jobs(),partitions() function article format
  docs/sql-manual/sql-functions/table-functions/numbers.md
  docs/sql-manual/sql-functions/table-valued-functions/jobs.md
  docs/sql-manual/sql-functions/table-valued-functions/numbers.md
  docs/sql-manual/sql-functions/table-valued-functions/partitions.md
  docs/sql-manual/sql-functions/table-valued-functions/query.md
  docs/sql-manual/sql-functions/table-valued-functions/tasks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/jobs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/numbers.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/partitions.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/tasks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/jobs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/numbers.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/partitions.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/tasks.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/jobs.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/numbers.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/partitions.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/query.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/tasks.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/table-functions/numbers.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/jobs.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/numbers.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/partitions.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/query.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/tasks.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-functions/numbers.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/jobs.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/numbers.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/partitions.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/query.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/tasks.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1846 [doc] Merge json_parse_* docs into json_parse zh_doc
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
Labels: bug, approved

#1829 [doc] Fix some json function zh_doc
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/json-functions/json-exists-path.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/json-functions/json-set.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-exists-path.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-set.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/jsonb-extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-exists-path.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-quote.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-set.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/jsonb-extract.md
Labels: has comments

#1843 [doc]Refresh table statement document modification
  docs/sql-manual/sql-statements/table-and-view/table/CANCEL-ALTER-TABLE.md
  docs/sql-manual/sql-statements/table-and-view/table/DESC-TABLE.md
  docs/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-CREATE-TABLE.md
  docs/sql-manual/sql-statements/table-and-view/table/TRUNCATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/CANCEL-ALTER-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/DESC-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/TRUNCATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/CANCEL-ALTER-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/DESC-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/TRUNCATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/CANCEL-ALTER-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/DESC-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-CREATE-TABLE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/TRUNCATE-TABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/CANCEL-ALTER-TABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/DESC-TABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-CREATE-TABLE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/TRUNCATE-TABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/CANCEL-ALTER-TABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/DESC-TABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/DROP-TABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-CREATE-TABLE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/TRUNCATE-TABLE.md
Labels: bug, request review

#1744 [fix] Fix data-model/unique typo (#1743)
  docs/table-design/data-model/unique.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/unique.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/unique.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/unique.md
  versioned_docs/version-2.1/table-design/data-model/unique.md
  versioned_docs/version-3.0/table-design/data-model/unique.md
Labels: approved

#1862 [doc] Fix json_fun_* en_doc
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-exists-path.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-extract.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-insert.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-object.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-quote.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-replace.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-set.md
  docs/sql-manual/sql-functions/scalar-functions/json-functions/json-unquote.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-exists-path.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-extract.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-insert.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-object.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-quote.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-replace.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-set.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-unquote.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/jsonb-extract.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-exists-path.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-extract.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-insert.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-object.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-parse.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-quote.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-replace.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-set.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-unquote.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/jsonb-extract.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review

#1811 [opt](functions) update some numeric functions docs
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/tan.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/tanh.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/truncate.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/uuid_numeric.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/width-bucket.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/tan.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/tanh.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/truncate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/uuid_numeric.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/width-bucket.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/tan.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/tanh.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/truncate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/uuid_numeric.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/width-bucket.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/tan.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/tanh.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/truncate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/uuid_numeric.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/width-bucket.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/tan.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/tanh.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/truncate.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/uuid_numeric.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/width-bucket.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/sqrt.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/tan.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/tanh.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/truncate.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/uuid_numeric.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/width-bucket.md
Labels: approved

#1852 [doc](sql) bitmap-1 func
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-count.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not-count.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-contains.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-count.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-empty.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-array.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-base64.md
  docs/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-string.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-contains.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-string.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-contains.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-string.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-contains.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-string.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-count.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not-count.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-contains.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-count.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-empty.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-array.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-base64.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-string.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-count.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not-count.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and-not.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-and.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-contains.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-count.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-empty.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-array.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-base64.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/bitmap-functions/bitmap-from-string.md
Labels: approved

#1839 [doc](sql) system func
  docs/sql-manual/sql-functions/scalar-functions/system-functions/connection-id.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/current-catalog.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/current-user.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/database.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/last-query-id.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/password.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/session-user.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/user.md
  docs/sql-manual/sql-functions/scalar-functions/system-functions/version-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/connection-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/current-catalog.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/current-user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/database.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/last-query-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/password.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/session-user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/system-functions/version-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/connection-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/current-catalog.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/current-user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/database.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/last-query-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/password.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/session-user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/version-function.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/connection-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/current-catalog.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/current-user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/database.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/last-query-id.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/password.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/session-user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/user.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/version-function.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/connection-id.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/current-catalog.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/current-user.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/database.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/last-query-id.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/password.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/session-user.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/user.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/system-functions/version-function.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/connection-id.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/current-catalog.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/current-user.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/database.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/last-query-id.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/password.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/session-user.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/user.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/system-functions/version-function.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1845 [opt](function) optimize some struct function docs
  docs/sql-manual/sql-functions/scalar-functions/struct-functions/named-struct.md
  docs/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
  docs/sql-manual/sql-functions/scalar-functions/struct-functions/struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/struct-functions/named-struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/struct-functions/struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/named-struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/named-struct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/named-struct.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/named-struct.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct.md
Labels: approved

#1853 improve Backup and Restore Statements SQL Manual
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
  docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
Labels: approved

#1797 [Fix](doc) fix Build docs with ldb toolchain
  community/source-install/compilation-with-ldb-toolchain.md
  i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install/compilation-with-ldb-toolchain.md
Labels: approved

#1816 [doc] Modify the documentation of functions of array_map, array_max, array_min, array_popback, array_popfront, array_position
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-map.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-max.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-min.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-popback.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-popfront.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-position.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-max.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-min.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-popback.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-popfront.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-position.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/bitwise-functions/bit-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-max.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-min.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-popback.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-popfront.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-position.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-map.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-max.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-min.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-popback.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-popfront.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-position.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-map.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-max.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-min.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-popback.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-popfront.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-position.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-map.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-max.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-min.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-popback.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-popfront.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-position.md
Labels: approved

#1882 [doc](import) add tp load to datasource
  docs/data-operate/import/data-source/migrate-data-from-other-oltp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/migrate-data-from-other-oltp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/migrate-data-from-other-oltp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/migrate-data-from-other-oltp.md
  sidebars.json
  versioned_docs/version-2.1/data-operate/import/data-source/migrate-data-from-other-oltp.md
  versioned_docs/version-3.0/data-operate/import/data-source/migrate-data-from-other-oltp.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: has comments

#1892 [doc] fix some agg functions doc
  docs/sql-manual/sql-functions/aggregate-functions/percentile-approx.md
  docs/sql-manual/sql-functions/aggregate-functions/percentile-array.md
  docs/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
  docs/sql-manual/sql-functions/aggregate-functions/quantile-union.md
  docs/sql-manual/sql-functions/aggregate-functions/regr-intercept.md
  docs/sql-manual/sql-functions/aggregate-functions/regr-slope.md
  docs/sql-manual/sql-functions/aggregate-functions/retention.md
  docs/sql-manual/sql-functions/aggregate-functions/sequence-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile-approx.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/quantile-union.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr-intercept.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr-slope.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/retention.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/sequence-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile-approx.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/quantile-union.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/retention.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/sequence-count.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile-approx.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile-array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/quantile-union.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/retention.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/sequence-count.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile-approx.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile-array.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/quantile-union.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/retention.md
  versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/sequence-count.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile-approx.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile-array.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/quantile-union.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/retention.md
  versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/sequence-count.md
  versioned_sidebars/version-2.1-sidebars.json
Labels: approved

#1910 [doc] fix some sql statements doc
  docs/sql-manual/sql-statements/account-management/GRANT-TO.md
  docs/sql-manual/sql-statements/account-management/REFRESH-LDAP.md
  docs/sql-manual/sql-statements/account-management/REVOKE-FROM.md
  docs/sql-manual/sql-statements/account-management/SET-LDAP_ADMIN_PASSWORD.md
  docs/sql-manual/sql-statements/account-management/SET-PROPERTY.md
  docs/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  docs/sql-manual/sql-statements/account-management/SHOW-PRIVILEGES.md
  docs/sql-manual/sql-statements/account-management/SHOW-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/GRANT-TO.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/REFRESH-LDAP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/REVOKE-FROM.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SET-LDAP_ADMIN_PASSWORD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SET-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SHOW-PRIVILEGES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/account-management/SHOW-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/GRANT-TO.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/REFRESH-LDAP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/REVOKE-FROM.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SET-LDAP_ADMIN_PASSWORD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SET-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-PRIVILEGES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/GRANT-TO.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/REFRESH-LDAP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/REVOKE-FROM.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SET-LDAP_ADMIN_PASSWORD.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SET-PROPERTY.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-PRIVILEGES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-PROPERTY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/GRANT-TO.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/REFRESH-LDAP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/REVOKE-FROM.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SET-LDAP_ADMIN_PASSWORD.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SET-PROPERTY.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-PRIVILEGES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/account-management/SHOW-PROPERTY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/GRANT-TO.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/REFRESH-LDAP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/REVOKE-FROM.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SET-LDAP_ADMIN_PASSWORD.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SET-PROPERTY.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-GRANTS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-PRIVILEGES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/account-management/SHOW-PROPERTY.md
Labels: approved

#1823 [doc] Add Computing Resource Management SQL Manual
  docs/sql-manual/sql-statements/cluster-management/compute-management/ALTER-RESOURCE.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/ALTER-WORKLOAD-GROUP.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/CREATE-WORKLOAD-GROUP.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/DROP-RESOURCE.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/DROP-WORKLOAD-GROUP.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/SHOW-RESOURCES.md
  docs/sql-manual/sql-statements/cluster-management/compute-management/SHOW-WORKLOAD-GROUPS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/ALTER-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/ALTER-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/CREATE-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/DROP-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/DROP-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/SHOW-RESOURCES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/compute-management/SHOW-WORKLOAD-GROUPS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/ALTER-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/ALTER-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/CREATE-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/DROP-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/DROP-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/SHOW-RESOURCES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/SHOW-WORKLOAD-GROUPS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/ALTER-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/ALTER-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/DROP-RESOURCE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/DROP-WORKLOAD-GROUP.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/SHOW-RESOURCES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/SHOW-WORKLOAD-GROUPS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/ALTER-RESOURCE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/ALTER-WORKLOAD-GROUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/CREATE-WORKLOAD-GROUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/DROP-RESOURCE.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/DROP-WORKLOAD-GROUP.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/SHOW-RESOURCES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/compute-management/SHOW-WORKLOAD-GROUPS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/ALTER-RESOURCE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/ALTER-WORKLOAD-GROUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-WORKLOAD-GROUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/DROP-RESOURCE.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/DROP-WORKLOAD-GROUP.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/SHOW-RESOURCES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/SHOW-WORKLOAD-GROUPS.md
Labels: request review

#1879 [doc](job)Optimize the documentation of job related statements
  docs/sql-manual/sql-statements/job/CREATE-JOB.md
  docs/sql-manual/sql-statements/job/DROP-JOB.md
  docs/sql-manual/sql-statements/job/PAUSE-JOB.md
  docs/sql-manual/sql-statements/job/RESUME-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/CREATE-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/DROP-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/PAUSE-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/RESUME-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/CREATE-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/DROP-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/PAUSE-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/RESUME-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/CREATE-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/DROP-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/PAUSE-JOB.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/RESUME-JOB.md
  versioned_docs/version-2.1/sql-manual/sql-statements/job/CREATE-JOB.md
  versioned_docs/version-2.1/sql-manual/sql-statements/job/DROP-JOB.md
  versioned_docs/version-2.1/sql-manual/sql-statements/job/PAUSE-JOB.md
  versioned_docs/version-2.1/sql-manual/sql-statements/job/RESUME-JOB.md
  versioned_docs/version-3.0/sql-manual/sql-statements/job/CREATE-JOB.md
  versioned_docs/version-3.0/sql-manual/sql-statements/job/DROP-JOB.md
  versioned_docs/version-3.0/sql-manual/sql-statements/job/PAUSE-JOB.md
  versioned_docs/version-3.0/sql-manual/sql-statements/job/RESUME-JOB.md
Labels: approved

#1858 exp function modify and dexp clear
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
  docs/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
  sidebars.json
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: approved

#1864 [doc] Modify the documentation of functions of array_distinct, array_enumerate,array_enumerate_uniq, array_except, array_exists,array_intersect, array_join
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-distinct.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate-uniq.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-except.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-exists.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-intersect.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-join.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-distinct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate-uniq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-except.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-exists.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-intersect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-join.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-distinct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate-uniq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-except.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-exists.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-intersect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-join.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-distinct.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate-uniq.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-except.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-exists.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-intersect.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-join.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-distinct.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate-uniq.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-except.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-exists.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-intersect.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-join.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-distinct.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate-uniq.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-enumerate.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-except.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-exists.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-intersect.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-join.md
Labels: request review

#1865 [doc] Modify the documentation of functions of array, array_apply, array_avg, array_compact, array_concat,array_cum_sum,array_difference
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-apply.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-avg.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-compact.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-concat.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array-difference.md
  docs/sql-manual/sql-functions/scalar-functions/array-functions/array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-apply.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-avg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-compact.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-concat.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-difference.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-apply.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-avg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-compact.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-concat.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-difference.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-apply.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-avg.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-compact.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-concat.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-difference.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-apply.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-avg.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-compact.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-concat.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-difference.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/array-functions/array.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-apply.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-avg.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-compact.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-concat.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array-difference.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/array-functions/array.md
Labels: approved

#1883 [Doc] Add vectorized functions
  docs/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
  docs/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
  docs/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
  docs/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
Labels: approved

#1935 [downlaod] update 2.1.8 release
  blog/ortege-studio-1-scaling-bitcoin-data-to-billions-of-records.md
  blog/ortege-studio-2-fine-tuning-apache-doris-for-maximum-performance-and-resilience.md
  blog/release-note-2.1.8.md
  blog/release-note-3.0.0.md
  docs/releasenotes/all-release.md
  docs/releasenotes/v2.1/release-2.1.8.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v2.1/release-2.1.8.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v2.1/release-2.1.8.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/all-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v2.1/release-2.1.8.md
  sidebars.json
  src/components/recent-blogs/recent-blogs.data.ts
  src/constant/download.data.ts
  src/constant/newsletter.data.ts
  src/pages/ecosystem/cluster-management/index.tsx
  static/images/2.1.8.jpg
  versioned_docs/version-2.1/releasenotes/all-release.md
  versioned_docs/version-2.1/releasenotes/v2.1/release-2.1.8.md
  versioned_docs/version-3.0/releasenotes/all-release.md
  versioned_docs/version-3.0/releasenotes/v2.1/release-2.1.8.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-3.0-sidebars.json
Labels: request review

#1860 [doc]str func
  docs/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
  docs/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
  docs/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
Labels: approved

#1805 [Fix](docs) Sql function months_add and months_sub
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/months-add.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/months-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/months-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/months-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/months-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/months-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/months-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/months-sub.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/months-add.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/months-sub.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/months-add.md
  versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/months-sub.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/months-add.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/months-sub.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/months-add.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/months-sub.md
Labels: approved

#1856 [doc]date func
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/extract.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampadd.md
  docs/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampdiff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampadd.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampdiff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampadd.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampdiff.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/extract.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampadd.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampdiff.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/extract.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampadd.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampdiff.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/extract.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampadd.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/timestampdiff.md
Labels: approved

#1889 improve partition_values() function article format
  docs/sql-manual/sql-functions/table-valued-functions/partition-values.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/partition-values.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/partition-values.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/partition-values.md
  versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/partition-values.md
  versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/partition-values.md
Labels: has comments

#1913 Fix hll function
  docs/sql-manual/sql-functions/scalar-functions/hll-functions/hll-cardinality.md
  docs/sql-manual/sql-functions/scalar-functions/hll-functions/hll-empty.md
  docs/sql-manual/sql-functions/scalar-functions/hll-functions/hll-from-base64.md
  docs/sql-manual/sql-functions/scalar-functions/hll-functions/hll-hash.md
  docs/sql-manual/sql-functions/scalar-functions/hll-functions/hll-to-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/hll-functions/hll-cardinality.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/hll-functions/hll-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/hll-functions/hll-from-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/hll-functions/hll-hash.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/hll-functions/hll-to-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/hll-functions/hll-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/hll-functions/hll-hash.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/hll-functions/hll-cardinality.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/hll-functions/hll-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/hll-functions/hll-hash.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-cardinality.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-from-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-hash.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-to-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-cardinality.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-empty.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-from-base64.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-hash.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-to-base64.md
  versioned_docs/version-1.2/sql-manual/sql-functions/hll-functions/hll-empty.md
  versioned_docs/version-1.2/sql-manual/sql-functions/hll-functions/hll-hash.md
  versioned_docs/version-2.0/sql-manual/sql-functions/hll-functions/hll-cardinality.md
  versioned_docs/version-2.0/sql-manual/sql-functions/hll-functions/hll-empty.md
  versioned_docs/version-2.0/sql-manual/sql-functions/hll-functions/hll-hash.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-cardinality.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-empty.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-from-base64.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-hash.md
  versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/hll-functions/hll-to-base64.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-cardinality.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-empty.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-from-base64.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-hash.md
  versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/hll-functions/hll-to-base64.md
Labels: request review

#1898 [doc](show table)Optimize the documentation of show table statements.
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-ID.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-STATUS.md
  docs/sql-manual/sql-statements/table-and-view/table/SHOW-TABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-STATUS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/SHOW-TABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-STATUS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-TABLES.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-ID.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-STATUS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-TABLES.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-ID.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-STATUS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/SHOW-TABLES.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-ID.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-TABLE-STATUS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/SHOW-TABLES.md
Labels: approved

#1921 delete show query profile for version>-2.1
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/queries/SHOW-QUERY-PROFILE.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/queries/SHOW-QUERY-PROFILE.md
Labels: approved

#1871 Function class management statement
  docs/sql-manual/sql-statements/function/DROP-FUNCTION.md
  docs/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
  docs/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/DROP-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-FUNCTIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/DROP-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/DROP-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-FUNCTION.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-CREATE-FUNCTION.md
  versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-FUNCTIONS.md
  versioned_docs/version-2.1/sql-manual/sql-statements/function/DROP-FUNCTION.md
  versioned_docs/version-2.1/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
  versioned_docs/version-2.1/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
  versioned_docs/version-3.0/sql-manual/sql-statements/function/DROP-FUNCTION.md
  versioned_docs/version-3.0/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
  versioned_docs/version-3.0/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
Labels: approved

#1945 [fox] Fix 2.1.8 typo and dead link
  blog/release-note-2.1.8.md
  docs/releasenotes/v2.1/release-2.1.8.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/v2.1/release-2.1.8.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/export/outfile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/v2.1/release-2.1.8.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/export/outfile.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/releasenotes/v2.1/release-2.1.8.md
  versioned_docs/version-2.1/data-operate/export/outfile.md
  versioned_docs/version-2.1/releasenotes/v2.1/release-2.1.8.md
  versioned_docs/version-3.0/data-operate/export/outfile.md
  versioned_docs/version-3.0/releasenotes/v2.1/release-2.1.8.md
Labels: approved

#1905 [doc]modify show transaction doc
  docs/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
  versioned_docs/version-2.1/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
  versioned_docs/version-3.0/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
Labels: request review
